### ISSUE TITLE
[Bug] <hitomi.la> : < i cannot read or download chapters>

### ISSUE THREAD

**Issue by Samy-darker** [inorichi/tachiyomi-extensions#4819] opened 2020-11-08 09:11 UTC
---

## Device information
- Tachiyomi version: 0.10.5
- Android version: 7

## Source information
- Name: hitomi.la
- Extension version: 1.2.3

## Steps to reproduce
1. First Step
Search for some manga : 
-Bricola 
-GAMEZ:0
ect...

2. Second Step
Try to read/download the chapters

### Expected behavior
This should have happened:
Read or download manga chapter

### Actual behavior
This happens instead:
Stuck "Retry" button appear on all chapter pages / no possibility to download chapter

## Other details

This problem is known for some manga (some i montioned above..) in the extension, while some other manga can be read/downloaded. Btw These manga work fine on the the official website.

**Comment by scb261** [comment] 2020-11-08 09:42
Duplicate of #4679

**Closed** 2020-11-08 12:53 UTC
Labels: bug
