### ISSUE TITLE
[Feature Request] Custom double tap zoom

### ISSUE THREAD

**Issue by johnlg91** [inorichi/tachiyomi-extensions#3188] opened 2020-05-16 14:57 UTC
## Issue/Request
For my experience the zoom in tachiyomi works by 'stretching' the image to a given resolution(this an assumption by me) , instead for example dividing the current image resolution by 2.
This creates issues because not all images are the same resolution, some mangas or sources are higher quality than others, so the amount of zoom you get with a double tap can vary quiet a lot. 

So I think it will be a great implementation to have a more consistent type of zoom system and later on give the user the ability to choose the amount of zoom a double tap makes. 
Another feature I remember from manga rock is the ability to keep the zoom across pages, instead of just zooming back again on every page, would be really useful in 4-komas or maybe implement a 4-koma reading mode all together. 
## Other details
I've recorded a video with a few examples of the varying zoom, if you think it would be useful please let me know where to upload it.
Here are some screenshots with and without double taping examples. 
![Screenshot_20200516-115318](https://user-images.githubusercontent.com/32649164/82122791-0d158e00-976c-11ea-825b-f6431365b3ca.jpg)
![Screenshot_20200516-115314](https://user-images.githubusercontent.com/32649164/82122792-0edf5180-976c-11ea-9a3b-c83f49781981.jpg)
![Screenshot_20200516-115239](https://user-images.githubusercontent.com/32649164/82122794-0f77e800-976c-11ea-921f-1232140e94b0.jpg)
![Screenshot_20200516-115231](https://user-images.githubusercontent.com/32649164/82122797-10a91500-976c-11ea-9224-3e22973f831f.jpg)
![Screenshot_20200516-115350](https://user-images.githubusercontent.com/32649164/82122798-11da4200-976c-11ea-94a3-768aec2320fd.jpg)
![Screenshot_20200516-115341](https://user-images.githubusercontent.com/32649164/82122799-130b6f00-976c-11ea-8b8c-415bccbc4730.jpg)

**Comment by arkon** [comment] 2020-05-16 15:52
Duplicate of https://github.com/inorichi/tachiyomi/issues/476

**Closed by arkon** 2020-05-16 15:52 UTC
