### ISSUE TITLE
[Source Request] <Rocaca>

### ISSUE THREAD

**Issue by DieSmilePN** [inorichi/tachiyomi-extensions#3872] opened 2020-07-22 16:31 UTC
### Source Website
- Name: Rocaca
- Link: http://rocaca.com/
- Language(s): English

**Comment by SnakeDoc83** [comment] 2020-07-22 16:43
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/587

**Closed by SnakeDoc83** 2020-07-22 16:43 UTC
Labels: Source Request
