### ISSUE TITLE
MangaDex search doesn't work / 403 and 503 errors

### ISSUE THREAD

**Issue by Asbesbopispa** [inorichi/tachiyomi-extensions#871] opened 2019-03-05 16:26 UTC
Workaround in MangaDex extension version 1.2.52+:

1. Search for manga on MangaDex website
2. Get ID from URL (e.g. "22521" from mangadex.org/title/22521/isekai-nonbiri-nouka)
3. In Tachiyomi, open MangaDex catalogue
4. Search for "id:22521"

Original post:

---

Hey there, I get "No results found" when searching manga on MangaDex. Could it be related to this?
https://www.reddit.com/r/manga/comments/axec45/psa_mangadex_is_being_ddosed_again
The admin reported he put some preventive measures.

**Comment by CarlosEsco** [comment] 2019-03-05 16:52
Will be resolved when they aren't being ddos

**Comment by Asbesbopispa** [comment] 2019-03-05 18:28
Thank you for your answer, I will report back if there are still issues after the ddos.

**Comment by Izuzusama** [comment] 2019-03-06 03:16
They seems to have deactivated public search for now thus the search fails

**Comment by SyntaxError1871** [comment] 2019-03-06 07:11
Same issue here. Will wait for them to fix on their end I guess.

**Comment by Asbesbopispa** [comment] 2019-03-07 00:32
Update on the situation
https://mangadex.org/thread/64354

**Comment by mishugashu** [comment] 2019-03-07 04:11
They are restricting searching to user accounts for the foreseeable future, even after the DDOS dies down. They won't be allowing it until they completely reimplement the search function, it sounds like.

Is it possible to implement a way to log in via Tachiyomi like we had with Batoto?

**Comment by crazy4ever** [comment] 2019-03-07 07:44
"We are still under a DDoS that has forced us to disable the search function for guests since that is their attack vector and it will most likely be disabled for the foreseeable future until the Dev team releases the new, improved version."

Oh boy, I really hope that you guys change your minds about considering to implement a login system, as it could take as long as a year before MangaDex resolvew this.

**Comment by CarlosEsco** [comment] 2019-03-08 10:06
Reopening so duplicate tickets aren't opened

**Comment by SyntaxError1871** [comment] 2019-03-09 02:37
At the very least is there any way to force Tachiyomi to a specific manga in the app if search doesn't work like a URL? There are a few new manga I picked up and being unable to at least add them in the app for offline downloading is frustrating.

**Comment by AlessandroMarinoni** [comment] 2019-03-10 03:11
Yeah, we should need a login creature (like TachiyomiEH does for EH) or at least a way to directly add one manga from the url.
I believe the latter would be the easiest to implement and fix the issue...

**Comment by arkon** [comment] 2019-03-10 20:28
Hijacking this to provide an update for people who end up finding this thread:

---

MangaDex isn't working in Tachiyomi while they work on mitigating the DDoS on their end. Check MangaDex's website or Discord server for more info.

**Comment by RatchetNine76** [comment] 2019-03-11 14:16
Just found a workaround for seraching manga. Works on version 1.2.52(dont know if old version works)

when typing in search, type **id:** then manga's id number from address bar. example:

manga Isekai Nonbiri Nouka - https://mangadex org/title/**22521**/isekai-nonbiri-nouka

in tachiyomi search, type: **id:22521**
22521 comes from the link.
credits go to: Undead_Soviet from mangadex Discord

**Comment by Izuzusama** [comment] 2019-03-11 14:20
> Works on version 1.2.52(dont know if old version works)

This just got introduced at version 1.2.52 so it wont work on older version at PR #886

**Comment by LoLyeah** [comment] 2019-03-11 23:00
And now, I got HTTP 403 error when opening Mangadex source and refreshing manga from Mangadex. Is it related to this issue or another whole new issue?

**Comment by Ramon20000** [comment] 2019-03-12 05:33
The 403 is most likely caused by cloudflare asking for you to fill a recaptcha before entering the site.

**Comment by AlessandroMarinoni** [comment] 2019-03-20 21:59
True: I've completed the recaptcha on Chrome, but I still get error 403 from the app.
Not even the id:[number] feature works

**Comment by charnezzed** [comment] 2019-03-25 02:58
Same for me with 403 errors. Filling out recaptcha did not resolve the issue, MangaDex is all 403 errors from Tachiyomi.

**Comment by Sparh4wk** [comment] 2019-03-29 00:12
Using latest catalogue version, but  search doesn't work for me. I can read any Mangas that I have in library and I can even see the latest. But when I wanna search for something it always gives me no results found error.

**Comment by Ramon20000** [comment] 2019-03-29 01:40
@Sparh4wk , the search for unlogged users is currently disabled due to the DDoS, as a workaround search it on a browser then use `id:[number]` on the catalogue search ([number] being the number on the url).

**Comment by rileypmills** [comment] 2019-04-01 05:07
Seems like the 403 workaround is hit or miss.  I think if Cloudflare isn't in super lockdown mode, opening one of the pages and completing the captcha will work.  But seems like whenever the site's busy (late CST) it stops working and searches, manga chapters, manga info refreshes, etc. all stop working no matter what I do with the site.

**Comment by terrym0** [comment] 2019-04-01 11:57
Yeah I'm getting the 403 error again too. Checked both latest build and latest dev build.

**Comment by jdanielchg** [comment] 2019-04-07 09:41
Are they still getting DDoS? It's weird because I can't open the catalog or search with my wifi connection, but I can with my mobile data, why is that?

**Comment by CarlosEsco** [comment] 2019-04-07 10:59
No but search is disabled for guest still.      If you really need search  to I have a mangadex only fork under my repositories

**Comment by Sparh4wk** [comment] 2019-04-07 11:08
@CarlosEsco if you dont intend to merge it to official, can you please make an apk for ppl who want to use search when you have some spare time? I think a lot of ppl would appreciate it.

**Comment by CarlosEsco** [comment] 2019-04-07 11:41
@sparh4wk I have an apk under mangadex repository but it's a separate app forked from main tachiyomi

**Comment by Sparh4wk** [comment] 2019-04-07 11:44
@CarlosEsco sry for bothering you.. I was blind :) I looked on that externsion fork and not mangadex.. thanks!!

**Comment by lhw** [comment] 2019-04-07 21:03
All api calls now return 503 for mangadex. Even with the website open in a browser on the same device. So I am guessing they changed their endpoints and this is now unrelated to the cloudflare mitigation that is now supposedly turned off for most things anyway.

**Comment by CarlosEsco** [comment] 2019-04-07 21:23
Must be region specific or you got ip banned cause it works fine for me

**Comment by jdanielchg** [comment] 2019-04-07 22:57
It now says "SyntaxError: Parse Error (line 1)" 
.

**Comment by inorichi** [comment] 2019-04-08 00:06
Can anyone confirm if the last dev version works?

**Comment by AlessandroMarinoni** [comment] 2019-04-08 00:11
I'm using Tachiyomi 0.8.2 and MangaDex plugin version 1.2.53 and everything works perfectly, including the "id:" workaround

**Comment by jdanielchg** [comment] 2019-04-08 00:13
@inorichi it works.

**Comment by inorichi** [comment] 2019-04-08 00:19
Cool. If anyone is still getting a 403, can you try a new option in the manga info called "open in web view"? It's slightly different from browser since this actually shares the cookies and user-agent with okhttp (the lib we use for networking)

You need r1488 to test

**Comment by lhw** [comment] 2019-04-08 21:52
Checked it with logs. Was just a cloudflare issue. Clearing cookies and dns cache fixed my issue.

**Comment by rileypmills** [comment] 2019-04-10 16:15
Yep, the "Open in Webview" option seems to be working.  Was able to get through a Cloudflare prompt and other app functionality started working again.

**Comment by Ballistic-Fruit** [comment] 2019-04-10 19:08
Is there any way to get the search and add function working again? I'm using Tachiyomi 0.8.2 and MangaDex 1.2.53, I've cleared my cache and cookies, and when I try to search the catalogue I get a message saying "com.squareup.duktape.DuktapeException: Syntax Error: invalid return..." I've accessed the manga I already had in my library using the "Open in Browser" option and bypassed the Captcha, but still nothing.

**Comment by drakellion** [comment] 2019-04-10 20:32
I have the same problem. Till yesterday it was fine but today I have the same ducktape error. I am using the stable build 0.8.2 and. 53 version of manga dex. Nothing had change in my settings sine yesterday

**Comment by arkon** [comment] 2019-04-10 20:36
Duktape issues is documented in #980

**Comment by ReGtrs** [comment] 2019-04-13 11:06
I don't know if this has been mentioned but I got to make Dex's search work through global and inside the source. I opened a manga from the source and opened the manga in web view and logged in.

**Comment by Asbesbopispa** [comment] 2019-04-14 01:05
@inorichi I'm often getting HTTP error 503 when reading Manga on the stable version of the app.
On the dev one, it works without problems. I logged in with the WebView option (I have Bromite WebView installed on my phone) and I can even search without using the id method.

**Comment by daxtron2** [comment] 2019-04-14 03:39
Can confirm @ReGtrs suggestion of logging in in the web view works. Not sure if it persists through closing/opening the app. v0.8.4

**Comment by ReGtrs** [comment] 2019-04-14 03:51
Just tested. Cookies are maintained ever after closing the app so the search still functions.

**Comment by feelerman** [comment] 2019-04-14 18:00
cannot use webview to solve captcha if no manga in library and latest just gives 403 since a view days ago.

tachiyomi 0.84 mangadex 1.2.54 android 8.1.0
latest dev version of tachiyomi also does not work

**Comment by Mystique0414** [comment] 2019-04-17 02:34
Its has also the same Issue in Mangahasu, I was planning to download from mangahasu bur it says 503 error. I have the the latest tachiyomi app and extension

**Comment by loocool2** [comment] 2019-04-17 02:37
If you have access to Mangahasu manga in your library, you will need to open that manga in webview and do the verification that way

**Comment by Samk19** [comment] 2019-04-17 08:01
Mangadex search not working in ver 0.8.4

**Comment by aghebert** [comment] 2019-04-19 02:15
Signing in with webview allows me to access Mangadex until I close the app, at which point cookies are erased and I need to sign in again.

**Comment by Samk19** [comment] 2019-04-19 12:57
Mangadex search working but with a catch 
Use  id to search for manga.....id can be found on url on the manga when viewing it on the browser

Alternatively can use this method:
1. Clear browser default
2.open chrome browser 
3.go to mangadex search manga 
4.when click on manga title an android popup will occur and will ask to open with (chrome / tachiyomi:mangadex external/browser)....select tachiyomi mangadex extension.....done

**Comment by AlessandroMarinoni** [comment] 2019-04-19 12:59
It is a very good idea, to add link recognition to Tachiyomi if it's possible

**Comment by inorichi** [comment] 2019-04-19 13:10
> Mangadex search not working in ver 0.8.4

If you're logged in, you have to use the default view in your mangadex account. The extension can't parse the other ones. I don't have an account but I've been told there are 4 different views.

> Signing in with webview allows me to access Mangadex until I close the app, at which point cookies are erased and I need to sign in again.

I think you're closing the app too soon. The system flushes cookies after a while (I can't do anything there), if you close the app before that happens they'll be lost.

> It is a very good idea, to add link recognition to Tachiyomi if it's possible

That's what he explained...

**Comment by CarlosEsco** [comment] 2019-04-19 13:21
also helps if when you login you click remember me.  as their cookies setting forces login every day if not

**Comment by Pzrs** [comment] 2019-04-19 18:54
So this morning I created a mangadex account, logged into it on my Chrome browser, and got everything working (tested by reading a few chapters before work).

During my lunch break I went to read a few more chapters and got the 403 error again and now I can't correct it either by logging out and back in of mangadex, clearing cache/cookies both from my browser and the app, uninstalling/reinstalling the mangadex extension, or setting the mangadex extension as the default (idk why but doing this instead makes it so that as far as I can tell nothing happens at all when trying to click Manga titles in Chrome, goes through a loading process and then sits there without opening anything unless I open in another tab)

I feel like there's maybe something simple that I'm missing but I can't figure out why it suddenly stopped working in the middle of the day.

**Comment by mishugashu** [comment] 2019-04-19 19:24
@Pzrs you need to use the dev version, go to the info page of a manga, click on the menu, click on "view in webview" and use the capcha and log in through that. It's a pretty big workaround, which I assume is why this bug is still open.

**Comment by Ramon20000** [comment] 2019-04-19 20:05
@mishugashu Pretty sure that the webview is already in stable.

**Comment by mishugashu** [comment] 2019-04-19 20:35
> @mishugashu Pretty sure that the webview is already in stable.

Whoops, you are correct. I wasn't paying attention to stable releases.

**Comment by zedoax** [comment] 2019-05-01 14:23
Can confirm. I'm able to use the search feature from the extension no problem. I logged in through the webview, and it fixed the 403 error as well as restored search. 

I am running stable for both tachiyomi and the mangadex extension

**Comment by Ballistic-Fruit** [comment] 2019-05-01 18:09
Am I just a total idiot? I can get into MangaDex just fine with both the webview option and browser option from the "info" section of any titles I already had loaded. They also retrieve updates with absolutely no problems. However, searching the catalogue for new titles to add just returns "No Results Found" every time I try.

**Comment by Ramon20000** [comment] 2019-05-01 18:11
@Ballistic-Fruit Did you log in into your mangadex account in webview?

**Comment by Ballistic-Fruit** [comment] 2019-05-01 18:22
Yes, I did. I can use any of the titles I have in my library, right?

**Comment by arkon** [comment] 2019-05-02 03:53
If you're getting "No results found" when trying to browse MangaDex after logging in, set your view mode to "Detailed" on https://mangadex.org/titles

**Comment by Ballistic-Fruit** [comment] 2019-05-02 16:48
@arkon That totally fixed it. Wow, what a dumb bug. Everything seems to work perfectly now. Thank you.

**Comment by marcosmt** [comment] 2019-05-03 16:41
I did all of that and mangadex extension still doesn't work

**Comment by akielijan** [comment] 2019-05-03 22:20
Okay, even doing all of these things doesn't make it work.

Tachiyomi version: stable 0.8.4
Manga Dex extension: 1.2.54
Logged both via browser & webview to my MangaDex account
View selected: detailed

MangaDex works fine via browser, but Tachiyomi seems to get a bunch of 403s.

**Comment by Yorshkka** [comment] 2019-05-04 00:19
Am i stupid, is there a work around for this?

Tachiyomi 0.8.4
Mangadex 1.2.54

Getting a bunch of 403s
Cant use the above workarounds
I can't open any manga in webview as there are none in my library due to restoring from a backup.

**Comment by matryosha** [comment] 2019-05-04 21:47
> Okay, even doing all of these things doesn't make it work.
> 
> Tachiyomi version: stable 0.8.4
> Manga Dex extension: 1.2.54
> Logged both via browser & webview to my MangaDex account
> View selected: detailed
> 
> MangaDex works fine via browser, but Tachiyomi seems to get a bunch of 403s. ID search doesn't work, too.

Open any manga from mangadex, then more options ( three dots on top right) and select open on webview. Solve the captcha and that's all

**Comment by KusanagiRyu** [comment] 2019-05-05 03:04
Nope, tried. Still getting 403 error

**Comment by thousandsofthem** [comment] 2019-05-05 15:23
> Open any manga from mangadex, then more options ( three dots on top right) and select open on webview. Solve the captcha and that's all

Works well for me. For new users there could be an issue with no discoverability - webview button is well hidden.  Having a copy of such button in "discover" would help a lot

**Comment by pandawang16** [comment] 2019-05-06 03:06
> > Open any manga from mangadex, then more options ( three dots on top right) and select open on webview. Solve the captcha and that's all
> 
> Works well for me. For new users there could be an issue with no discoverability - webview button is well hidden. Having a copy of such button in "discover" would help a lot

Doesn't work for me. Still having the error

**Comment by Sparh4wk** [comment] 2019-05-06 06:06
can confirm this.. everything was working fine with webview, but now its broken.. its works only sometimes and only for a few searches.. sometimes it works for search and then when I wanna add manga, it gives me error to loading chapters etc.. I think we need proper login method for this to work fine, or something else.

**Comment by c-h-u-c-k** [comment] 2019-05-06 06:31
I get solid 403 errors with the latest versions. Still broken.

**Comment by CarlosEsco** [comment] 2019-05-06 08:28
Login has nothing to do with 403 though

**Comment by c-h-u-c-k** [comment] 2019-05-06 11:18
I'm getting a 403 on any action not just searching.

**Comment by Sparh4wk** [comment] 2019-05-06 11:47
@CarlosEsco ye thats why I write or something else :) I dont have knowledge what causing this.
@c-h-u-c-k ye its not only search related :(

**Comment by CarlosEsco** [comment] 2019-05-06 13:10
The work around works.  Problem is they get ddos a lot so sometimes you have to do it more often. Predownload your chapters when it's not getting ddos and you have issues. If you still have issues with 403 or 503 it's user error.

**Comment by tollyx** [comment] 2019-05-07 20:45
Due to some new anti-ddos filter it seems like all the requests that tachiyomi is creating can trigger a cloudflare ip ban.

So it's time to implement a rate limiter if there isn't one already, I guess?

**Comment by Izuzusama** [comment] 2019-05-09 13:48
> Due to some new anti-ddos filter it seems like all the requests that tachiyomi is creating can trigger a cloudflare ip ban.
> 
> So it's time to implement a rate limiter if there isn't one already, I guess?

rate limit is implemented at 1.2.56
https://github.com/inorichi/tachiyomi-extensions/commit/f91bc2fdd1334e6bb92804bf52b74a77808dda1e#diff-48b00f02a22531f2096c4ebdbf27c3ee

**Comment by legion2150** [comment] 2019-05-09 20:34
Soo... I'm on a new device and importing backup file ended with tons of 403 errors from series on MangaDex.
I've tried  android thingy icon on the browser to launch specific manga in Tachiyomi but it ends up only showing the id and spinning the loading circle indefinitely.
Any ideas how to even add any manga to get to the webview/cloudflare/login?

**Comment by vampiricwulf** [comment] 2019-06-13 07:50
Still getting empty search results...

**Comment by gumyns** [comment] 2019-06-13 19:09
Just took a look on code, and all these queries basically work when you're logged in. Maybe a possibility to provide login option to extensions would fix that once and for all?

**Comment by vampiricwulf** [comment] 2019-06-13 20:13
You're right, I logged in while in web view mode and I was then able to
receive search results.
Looks like the extension needs a login ability.

**Comment by CarlosEsco** [comment] 2019-06-13 20:50
Read up. There's no login for extension use the webview.

**Comment by arkon** [comment] 2019-06-13 20:57
Logging in via the WebView is the recommended workaround.

**Closed** 2019-06-13 20:57 UTC
Labels: Known Issue, Workaround Available

**Comment by SamB** [comment] 2019-08-29 16:40
Is there some way that the extension could direct affected users to this issue page instead of just returning no results?

**Comment by ay3w** [comment] 2019-09-02 07:31
probably just better off to put something in either tachiymoi-extensions or the main repo's readme seeing how popular mangadex is.

**Comment by ravikiranp123** [comment] 2019-09-23 08:37
Here is what works for me.

1. Search for a manga on the website.
2. Click on the manga
3. Android's app selector opens up
4. Select tachiyomi
5. Bookmark in app.

I am on miui10 with Android 10 with a k20 pro. Try this out. It might help until things are sorted out.

**Comment by bbtora** [comment] 2019-09-23 09:41
Hi, you would need to log in the site to use search.
This is how you do it through the app > https://tachiyomi.org/help/faq/extensions.html#no-results-when-searching
