### ISSUE TITLE
[Bug] madara, wuxiaworld : page list empty

### ISSUE THREAD

**Issue by Mechanical-sanity** [inorichi/tachiyomi-extensions#1642] opened 2019-10-13 22:58 UTC
### Device information
* Tachiyomi extension version: 1.2.9
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1.open any manhua from the wuxiaworld extension from madara

### Expected behavior
The manhua should have opened and be able to read

### Actual behavior
The manhua does not open and instead it says page list is empty for literally all the manhuas

### Other details
None

**Comment by SnakeDoc83** [comment] 2019-10-13 23:11
Madara is up to version 1.2.18, update your extensions.

**Comment by Mechanical-sanity** [comment] 2019-10-14 01:36
Problem still persists even after updating

**Comment by happywillow0** [comment] 2019-10-14 01:54
Do you have any specific manhuas you can point us to to double check what you are seeing? 
I just downloaded Mandra / WuxiaWorld and Rebirth of the Unban... is loading properly. 

Have you checked out the [Tachiyomi website problem section](https://tachiyomi.org/help/guides/source-problems/)? What other steps have you tried? Have you tried loading the site via webview and the phone's browser to see if you can connect manually?

**Comment by Mechanical-sanity** [comment] 2019-10-14 14:20
Try battle frenzy

**Comment by SnakeDoc83** [comment] 2020-01-07 08:50
@Mechanical-sanity Is this still a problem for you?

**Comment by DumpDumpDump** [comment] 2020-01-07 17:01
Related to this, the same thing happened to Kissmanga.in (8 Jan 2020)

When I tried to open a chapter directly, it will shows page empty. If I open it by resume read, it will shows "HTTP Error 500"

Tachiyomi extension version: 1.2.42
Tachiyomi version: 0.8.4
Android version: 9

**Comment by SnakeDoc83** [comment] 2020-04-26 04:18
@arkon I use this source from time to time and I've never been able to reproduce this.  It's currently working and OP never replied when I tried to check in with them in January.  Further, Tachi has updated since then as well.  I'd close this.

**Closed** 2020-04-26 13:42 UTC
Labels: bug
