### ISSUE TITLE
[Source Request] Mad scientistss

### ISSUE THREAD

**Issue by el3rg** [inorichi/tachiyomi-extensions#4235] opened 2020-08-28 04:15 UTC
- Name: Mad scientistss
- Link: https://mad-scientistss.blogspot.com/?m=1
- Language(s): Arabic

**Comment by SnakeDoc83** [comment] 2020-08-28 04:26
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/2635

**Closed by SnakeDoc83** 2020-08-28 04:26 UTC
Labels: Source Request
