### ISSUE TITLE
[Feature Request] MangaDex: Filter chapters by scanlation groups

### ISSUE THREAD

**Issue by kalebC** [inorichi/tachiyomi-extensions#5000] opened 2020-12-02 22:44 UTC
As stated in the title, I was wondering if it's possible to implement something like this. If there are multiple groups scanlating a manga series, it can get pretty messy binge-reading/downloading multiple chapters, as after you finish reading a chapter the next one is the same, but with a different translation.

MangaDex.org has a neat little feature in the reader 
![mangadex](https://user-images.githubusercontent.com/12353487/100940278-665dc880-34d6-11eb-878a-d5dc78f241d5.png)
where you can choose which group you want to read the manga from. If such a feature was present in Tachiyomi it would prove very useful.

**Comment by scb261** [comment] 2020-12-02 23:01
Duplicate of https://github.com/inorichi/tachiyomi/issues/969

**Closed** 2020-12-02 23:08 UTC
Labels: enhancement
