### ISSUE TITLE
[Source Request] niadd.com

### ISSUE THREAD

**Issue by leox233** [inorichi/tachiyomi-extensions#3303] opened 2020-05-24 23:50 UTC
Name: niadd.com
Link: https://niadd.com
Language(s): All

**Comment by SnakeDoc83** [comment] 2020-05-24 23:52
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/1007 (though it's labeled Spanish, realistically it's the same).

**Closed by SnakeDoc83** 2020-05-24 23:52 UTC
Labels: Source Request
