### ISSUE TITLE
[Source Request Arabic] <gmanga>

### ISSUE THREAD

**Issue by REDAKUN** [inorichi/tachiyomi-extensions#4685] opened 2020-10-22 13:34 UTC
---

## Source Website
- Name: ? Gmanga
- Link: ? https://www.gmanga.me/
- Language(s): ? Arabic

## Other Details
Best arabic manga and manhwa website

**Comment by scb261** [comment] 2020-10-22 13:37
Duplicate of #117

**Closed** 2020-10-22 13:38 UTC
Labels: Source Request
