### ISSUE TITLE
[Source Request] MangaZone.cc

### ISSUE THREAD

**Issue by Mekelia** [inorichi/tachiyomi-extensions#4247] opened 2020-08-29 04:05 UTC
## Source Website
- Name: MangaZone
- Link: https://mangazone.cc
- Language(s): English

**Comment by SnakeDoc83** [comment] 2020-08-29 04:06
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/2622

**Closed by SnakeDoc83** 2020-08-29 04:06 UTC
Labels: Source Request

**Comment by ANETAIII** [comment] 2020-09-02 12:30
I asked this site too
It's not added? We can't have hope for it? This site is very useful!

**Comment by Mekelia** [comment] 2020-09-03 03:22
They said there was an error with it but that was months ago so I don't know if they figured it out
