### ISSUE TITLE
[Source Request] <smackjeeves>

### ISSUE THREAD

**Issue by sohilsayed** [inorichi/tachiyomi-extensions#3431] opened 2020-06-07 14:12 UTC
### Source Website
- Name: SmackJeeves
- Link: https://www.smackjeeves.com/
- Language(s): English and Spanish

### Other Details
They Have Comico Comics like Kakao 79% and Relife in english

**Comment by SnakeDoc83** [comment] 2020-06-08 00:30
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/3079

**Closed by SnakeDoc83** 2020-06-08 00:30 UTC
Labels: Source Request
