### ISSUE TITLE
[Source Request] <Manga3s>

### ISSUE THREAD

**Issue by dingdonng22** [inorichi/tachiyomi-extensions#4971] opened 2020-11-28 07:41 UTC
## Source Website
- Name: Manga3s
- Link: https://manga3s.com/
- Language(s): EN

## Other Details
uploads chinese korean japanese comics

**Comment by Riztard** [comment] 2020-11-28 13:49
Duplicate of #4518

**Closed** 2020-11-28 13:52 UTC
Labels: Source Request
