### ISSUE TITLE
[Bug] MangaLife (EN): One-Punch Man Chapter 0132.3 won't load

### ISSUE THREAD

**Issue by RzdAkira** [inorichi/tachiyomi-extensions#4987] opened 2020-12-01 14:03 UTC
## Device information
- Tachiyomi version: Stable 0.10.5
- Android version: 10

## Source information
- Name: MangaLife
- Extension version: English 1.2.10

## Steps to reproduce
1. Tap Browse > MangaLife > One-Punch Man
2. Tap chapter 132.3

### Expected behavior
The chapters should load and be readable/downloadable as usual

### Actual behavior
Chapter immediatelly closes and get kicked out to the chapter seklection screen. Error message "JSON document was not fully consumed" pops up.

## Other details
Apparently multiple chapters on One-Punch Man has this kind of behaviour. Currently: 98.2, 103.5, 111.5, 124.2 and132.2 as far as I know.
Downloading the chapters manually also does not work and simply causes "Error" to popped up.

**Comment by scb261** [comment] 2020-12-01 14:06
Duplicate of #4590

**Closed** 2020-12-01 14:15 UTC
Labels: bug
