### ISSUE TITLE
[Source Request] Alfie by Buttsmithy

### ISSUE THREAD

**Issue by emidelgado01** [inorichi/tachiyomi-extensions#3578] opened 2020-06-20 02:21 UTC
### Source Website
- Name: Alfie (by buttsmithy)
- Link: https://buttsmithy.com/
- Language(s): English

**Comment by magicisreals1234** [comment] 2020-07-28 03:48
bump, it's also on E-hentai /ex, you can use tachiyomiAZ for it

**Comment by AbdullahM0hamed** [comment] 2020-10-03 19:46
Duplicate of #2257

**Closed** 2020-10-03 19:47 UTC
Labels: Source Request
