### ISSUE TITLE
New Sources e.g. Fakku.net

### ISSUE THREAD

**Issue by melnation-com** [inorichi/tachiyomi-extensions#209] opened 2018-02-20 15:51 UTC
fakku.net

hitomi.la

tsumino.com

**Comment by CarlosEsco** [comment] 2018-02-20 15:56
Please title this for fakku.net like the other issues.  Hitomi and tsumino have already been requested and I believe EHTachiyomi fork supports those 2

**Comment by melnation-com** [comment] 2018-02-20 16:01
yeah but EHTachiyomi seems run by 1 man and buggish and slower bug fix.

I see new extension keep adding even tho most will never use them like the non-english extensions, I will not be asking more extensions after these, so I don't see what's the harm.

**Comment by ddmgy** [comment] 2018-02-20 16:54
It is unlikely that an extension could be written for Fakku. They require a paid subscription to access any manga, and the way they serve chapters makes it very difficult to scrape for images.

I'll take a look today to see if they have changed anything in the last few months, but I'm not optimistic.

**Comment by Intervencion** [comment] 2018-02-20 17:00
JDownloader have a plugin for Fakku, so it's doable.

The paid thing is as easy as adding a log-in feature. Like Batoto's have/had.

**Comment by ddmgy** [comment] 2018-02-20 19:23
> The paid thing is as easy as adding a log-in feature. Like Batoto's have/had.

My comment about a subscription has less to do with logging in from Tachiyomi (which will be possible at some point), and more about needing a subscription to access the chapters to see if it is even feasible to write the extension.

> JDownloader have a plugin for Fakku, so it's doable.

Do you have any experience using JDownloader with Fakku, in the last two years or so?

I've downloaded JDownloader and have tried to download several manga from Fakku, and it is not grabbing anything from the chapter. It finds a load of thumbnails that are not referenced anywhere on any link I try to download.

I've also looked through the source for the Fakku plugin, and it looks like it is set up to scrape the old site, from before Fakku turned into a paid subscription service.

**Comment by Intervencion** [comment] 2018-02-20 19:34
Interesting... I assumed was the paid one, my bad.

**Comment by paulo27ms** [comment] 2018-02-23 03:34
Scrapping it should still be possible as someone uploads new chapters to Nyaa every month.

**Comment by CarlosEsco** [comment] 2018-11-05 22:35
Dupe of #94

**Closed by CarlosEsco** 2018-11-05 22:35 UTC
Labels: Source Request
