### ISSUE TITLE
[Bug] <Bato.to>: Value document.domain of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by DieSmilePN** [inorichi/tachiyomi-extensions#4607] opened 2020-10-14 00:07 UTC
## Device information
* Tachiyomi version: v0.10.5 (standard, 2769e27a2, 51)
* Android version: 10 (SDK 29)

## Source information
* Source name: Bato.to  
* Source extension version: v1.2.2

## Issue/Request
I dont know why the bato.to doesn't show any content. I try to open in WebView the site is working and i even login. Maybe because the emerald extension. It updated the a week ago. Maybe the update crashed it?

## Other details
![20201014_075327](https://user-images.githubusercontent.com/68656846/95928294-97cde800-0df3-11eb-9822-acd0c84e0d71.png)

**Comment by arkon** [comment] 2020-10-14 00:19
Duplicate of #4524

**Closed by arkon** 2020-10-14 00:19 UTC
Labels: bug
