### ISSUE TITLE
[Source Request] remanga

### ISSUE THREAD

**Issue by RaCc0oN1** [inorichi/tachiyomi-extensions#3076] opened 2020-05-09 01:24 UTC
### Source Website
- Name: remanga
- Link: https://remanga.org
- Language(s): Russian

**Comment by SnakeDoc83** [comment] 2020-05-09 05:36
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/1886

**Closed** 2020-05-09 12:47 UTC
Labels: Source Request
