### ISSUE TITLE
[No Search] <Readm>: <Neither search nor filters work on the source> 

### ISSUE THREAD

**Issue by retrded1** [inorichi/tachiyomi-extensions#4870] opened 2020-11-13 23:13 UTC
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.5)

## Device information
- Tachiyomi version: 1.3.1 (preview build 305)
- Android version: 9

## Source information
- Name: Readm
- Extension version: 1.2.4

## Steps to reproduce
1. Type in search bar any keyword or even letter or press filter and filter by genre
2. Press search 

### Expected behavior
Manga under the following letter, keyword or filter should come up

### Actual behavior
Comes up with no results found 

## Other details
Happened today about 2 hours ago. Could be the website

**Comment by CrepeTF** [comment] 2020-11-13 23:22
Duplicate of #4858

**Closed** 2020-11-13 23:43 UTC
Labels: bug
