### ISSUE TITLE
[Extension Request]

### ISSUE THREAD

**Issue by Beaudu169** [inorichi/tachiyomi-extensions#1452] opened 2019-09-02 07:47 UTC
There is a website/app that is similar to webtoons which is called [Toomics](https://toomics.com/en) 
Is it possible to get that extension in Tachiyomi.

**Comment by SnakeDoc83** [comment] 2019-09-05 23:53
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/1120

**Closed** 2019-09-06 01:10 UTC
