### ISSUE TITLE
[Issue] Manhuaren new manga chapters remaining in "Today" category for a month

### ISSUE THREAD

**Issue by yogiwizard** [inorichi/tachiyomi-extensions#966] opened 2019-03-24 06:12 UTC
Tachiyomi version : vr1438
Extension version : v1.2.4
Extension name : manhuaren

New manga chapters from Manhuaren source will remain in Today's category under Library updates after the day has passed. These "new" chapters will continue showing up in today's category  for a period of 1 MONTH until it dropped out from the category.

Can something be done to correct this?

**Comment by yogiwizard** [comment] 2019-03-24 06:16
![](https://user-images.githubusercontent.com/46705106/52031883-942ffa00-2559-11e9-9bef-f1a55888df5c.jpg)

![](https://user-images.githubusercontent.com/46705106/52031888-96925400-2559-11e9-8c06-d6db8afe4094.jpg)

![](https://user-images.githubusercontent.com/46705106/52031891-97c38100-2559-11e9-926b-7d13af102827.jpg)

**Comment by SnakeDoc83** [comment] 2019-07-15 07:59
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/731

**Closed** 2019-07-15 09:38 UTC
