### ISSUE TITLE
[Source Request] <mangapill.com>

### ISSUE THREAD

**Issue by Ho3iwx** [inorichi/tachiyomi-extensions#4745] opened 2020-10-30 06:31 UTC
Source Website
- Name: mangapill
- Link: www.mangapill.com
- Language(s): English

Other Details
Best source for read and download manga high quality version.

**Comment by scb261** [comment] 2020-10-30 07:22
Duplicate of #4689

**Closed** 2020-10-30 12:32 UTC
Labels: Source Request
