### ISSUE TITLE
[Source Request] Manga blkom

### ISSUE THREAD

**Issue by rokogan** [inorichi/tachiyomi-extensions#3205] opened 2020-05-17 11:57 UTC
### Source Website
- Name: Manga blkom
- Link: manga.blkom.com
- Language(s): Arabic

**Comment by SnakeDoc83** [comment] 2020-05-17 17:16
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/1832

**Closed** 2020-05-17 17:22 UTC
Labels: Source Request
