### ISSUE TITLE
[Bug] Madara extension (allporncomics) : allporncomics not working again

### ISSUE THREAD

**Issue by fawadkhan121** [inorichi/tachiyomi-extensions#2069] opened 2020-01-14 16:15 UTC
### Device information
* Tachiyomi extension version: ?
* Tachiyomi version: ?
* Android version: ?

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by SnakeDoc83** [comment] 2020-01-15 22:04
@arkon I'm guessing the issue here is the Cloudflare "challenge not found" one.  There's a bunch of open issues on it now:

https://github.com/inorichi/tachiyomi-extensions/issues/2038
https://github.com/inorichi/tachiyomi-extensions/issues/2035
https://github.com/inorichi/tachiyomi-extensions/issues/2026
https://github.com/inorichi/tachiyomi-extensions/issues/1828

IMO they should all be closed, then make a new pinned issue with a better title (ideally one that doesn't make it seem like a source-specific issue).

**Comment by arkon** [comment] 2020-01-16 03:25
Duplicate of #2076

**Closed by arkon** 2020-01-16 03:25 UTC
Labels: bug
