### ISSUE TITLE
[Source Request] <Hentailxx>

### ISSUE THREAD

**Issue by ariyukigrey** [inorichi/tachiyomi-extensions#4616] opened 2020-10-15 05:58 UTC
## Source Website
- Name: Hentailxx
- Link: hentailxx.net
- Language(s): Vietnamese

## Other Details
It has plenty of hentai and manhwa, webtoon translated to Vietnamese

**Comment by arkon** [comment] 2020-10-15 12:29
Duplicate of #3052

**Closed by arkon** 2020-10-15 12:29 UTC
Labels: Source Request
