### ISSUE TITLE
when i try to read or download manga from that source it says "value document.domain of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by WhityNoise** [inorichi/tachiyomi-extensions#4555] opened 2020-10-08 07:30 UTC
## Device information
- Tachiyomi version: Preview r2763 (4cbe4977)
- Android version: 9

## Source information
- Name: Mangawindow
- Extension version: Emerald

## Steps to reproduce
1. Browse mangawindow source
2. Try to open any chapter of any manga there

### Expected behavior
Just opening chapter

### Actual behavior
It says "value document.domain of type java.lang.String cannot be converted to JSONObject
## Other details
Happened around 10.06.2020 and it was suddenly when i tried to read new chapter, then i checked other manga from that source and same thing happened. Bato.to suffering from the same problem.

**Comment by arkon** [comment] 2020-10-08 12:13
Duplicate of #4524

**Closed by arkon** 2020-10-08 12:13 UTC
Labels: bug
