### ISSUE TITLE
[Bug] HentaiVN: It's not working at all

### ISSUE THREAD

**Issue by ngovandang** [inorichi/tachiyomi-extensions#5124] opened 2020-12-13 20:04 UTC
## Device information
- Tachiyomi version: 0.10.6
- Android version: 10

## Source information
- Name: HentaiVN
- Extension version: 1.2.5

Hi Tachiyomi team,
As my tittle saying,
Well I tried many ways, clearing cookies, data, history, uninstall and reinstall, turn on cloudflare. But none of them is getting this extension to work.
Web view is fine and no problem, this already happen for 4 or 5 months.

Thank you for reading this also hope we are getting a fix soon.

**Comment by scb261** [comment] 2020-12-13 20:19
Probably duplicate of #3623, and I reproduced it before, but now everything is working fine for me. But looking at closed issue #3033 it seems, that it happens only for some users

**Comment by arkon** [comment] 2020-12-13 20:26
Let's keep this to #3623

**Closed by arkon** 2020-12-13 20:26 UTC
Labels: bug
