### ISSUE TITLE
[Source Request] <Gmanga>

### ISSUE THREAD

**Issue by motsouzumaki** [inorichi/tachiyomi-extensions#3899] opened 2020-07-26 01:12 UTC
Source Website

- Name: gmanga
- Link: https://gmanga.me
- Language(s): arabic

Other Details
The largest arabic manga library....I hope that you fulfill my request and thank you for your efforts

**Comment by SnakeDoc83** [comment] 2020-07-26 01:14
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/117

**Closed by SnakeDoc83** 2020-07-26 01:14 UTC
Labels: Source Request

**Comment by motsouzumaki** [comment] 2020-07-26 13:05
> Duplicate of #117

Oh no problem
