### ISSUE TITLE
[Source Request] <Mavi Manga>

### ISSUE THREAD

**Issue by Kebab-chan** [inorichi/tachiyomi-extensions#3548] opened 2020-06-16 19:25 UTC
### Source Website
- Name: Mavi Manga
- Link: https://mavimanga.com
- Language(s): Turkish

### Other Details
Manga information wordpress and reading side my manga reader cms (https://mavimanga.com/r)

**Comment by AbdullahM0hamed** [comment] 2020-10-03 19:48
Duplicate of #3266

**Closed** 2020-10-03 19:59 UTC
Labels: Source Request
