### ISSUE TITLE
[Source Request] Gmanga

### ISSUE THREAD

**Issue by alucardlucilfer** [inorichi/tachiyomi-extensions#2634] opened 2020-04-10 05:35 UTC
### Source Website
Website can be found at https://gmanga.me.

### Other Details
Arabic manga site

**Comment by SnakeDoc83** [comment] 2020-04-10 07:27
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/117

**Closed** 2020-04-10 10:36 UTC
Labels: Source Request
