### ISSUE TITLE
[Source Request] gmanga.me 

### ISSUE THREAD

**Issue by Amr-4** [inorichi/tachiyomi-extensions#2094] opened 2020-01-18 21:20 UTC
### Source Website
Website can be found at <website_url>.
Can you add gmanga.me rather than manga.ae
### Other Details
The chapter not founded in manga.ae and also not appear in liberty update
Thank you

**Comment by SnakeDoc83** [comment] 2020-01-18 21:29
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/117

**Closed** 2020-01-18 22:32 UTC
Labels: Source Request
