### ISSUE TITLE
[Source Request] HBrowse

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi-extensions#1630] opened 2019-10-10 11:27 UTC
### Source Website
The website for this source can be found [here](https://www.hbrowse.com/).

### Other Details
This extension is already in-built in the Tachiyomi-EH fork, so I *suppose* it should be easy to implement it as a separate extension as well. I'd really appreciate it, thanks.

**Comment by SnakeDoc83** [comment] 2019-10-10 19:46
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/1174

TachiyomiEH uses some custom stuff for this source, won't be a straight port.

**Closed** 2019-10-10 20:42 UTC
Labels: Source Request
