### ISSUE TITLE
[Source Request] <i like comix>

### ISSUE THREAD

**Issue by fawadkhan121** [inorichi/tachiyomi-extensions#4821] opened 2020-11-08 13:22 UTC
**PLEASE READ THIS**

I acknowledge that:

- I have checked that the extension does not already exist:
  - In the list of existing extensions in the application
  - In the multi-source spreadsheet: https://tachiyomi.org/extensions
  - By searching the GitHub repository for the extension and verify it does not appear in the code base
- I have searched the existing GitHub issues and this extension does **NOT** have an open request
- I will fill out the title and the information in this template

## Source Website
- Name: i like comix
- Link: https://ilikecomix.com/
- Language(s): english

## Other Details
Great new 18+ comics

**Comment by CrepeTF** [comment] 2020-11-08 13:29
Duplicate of #3550[](https://github.com/inorichi/tachiyomi-extensions/issues/3550)

**Closed** 2020-11-08 13:31 UTC
Labels: Source Request
