### ISSUE TITLE
[Source Request Arabic] <gmanga>

### ISSUE THREAD

**Issue by REDAKUN** [inorichi/tachiyomi-extensions#3820] opened 2020-07-17 19:00 UTC
---

### Source Website
- Name: ? Gmanga
- Link: ?https://www.gmanga.me/
- Language(s): ? Arabic

### Other Details
One of the best arabic manga website

**Comment by arkon** [comment] 2020-07-17 19:07
As mentioned in the template, please search for existing issues first.

Duplicate of #117

**Closed by arkon** 2020-07-17 19:07 UTC
Labels: Source Request
