### ISSUE TITLE
Ninemanga issue

### ISSUE THREAD

**Issue by Mloullin** [inorichi/tachiyomi-extensions#3320] opened 2020-05-26 05:01 UTC
### Device information
* Tachiyomi version: 9.2
* Android version: latest
* Device: galaxy s8

### Source information
* Source name: ninemanga
* Source extension version: 1.2.12

## Issue/Request
Cant browse ninemangaen and when i try to use webview it sends me to this a gardening site 
## Other details
Additional details and attachments.
![Screenshot_20200525-134731_Tachiyomi](https://user-images.githubusercontent.com/65937587/82861885-bf94e000-9f26-11ea-87e6-96afb0e93474.jpg)

**Comment by SnakeDoc83** [comment] 2020-05-26 06:24
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/3126

**Closed by SnakeDoc83** 2020-05-26 06:24 UTC
