### ISSUE TITLE
MangaRock not updating

### ISSUE THREAD

**Issue by felixalguzman** [inorichi/tachiyomi-extensions#569] opened 2018-10-19 23:09 UTC
When I refresh my library not all the mangas in mangarock are shown in the list of updates, only if I go to the specific ones and update there, sorry for bad english.

Mangarock version : 1.0.2
Tachiyomi version: 0.8.0

**Comment by arkon** [comment] 2018-10-20 04:15
Which manga?

**Comment by felixalguzman** [comment] 2018-10-20 04:32
Peerless Dad, Haikyuu!!, The God of HighSchool, D.I.C.E., God of Martial Arts and many others

**Comment by joseph619** [comment] 2018-11-03 14:59
Try switching to Mangadex to see if it works. Sometimes they update late. I have no issue on my end.

**Comment by as280093** [comment] 2019-03-10 10:08
Close this issue as the error is related to MangaRock side they don't update due to legal matters or if they don't have a source to scrap from, i have confirmed it from their support staff.

**Closed** 2019-03-10 11:54 UTC
