### ISSUE TITLE
webcomics page list empty

### ISSUE THREAD

**Issue by Mechanical-sanity** [inorichi/tachiyomi-extensions#1298] opened 2019-07-16 00:24 UTC
I'm using v0.8.4 of tachiyomi and the webcomics extension v1.2.1 and for some weird reason, I cant read any chapters of "taming the possesive girl" after chapter 20. I'm using the webcomics extension of course. The error says that "page list is empty." Soemthing is definatley wrong with the comic and maybe even the extension.

**Comment by hXtreme** [comment] 2019-07-16 00:34
Does it open and display property in web view?

**Comment by SnakeDoc83** [comment] 2019-07-16 00:42
Browsing their website, it looks like the source doesn't provider chapters past 20, instead they tell you to download their app.  So, that's an issue with the source, not Tachi.

**Comment by Mechanical-sanity** [comment] 2019-07-16 11:00
So what will happen with this extension?

**Comment by CarlosEsco** [comment] 2019-07-16 11:18
If possible it needs to ignore those ones

**Comment by arkon** [comment] 2019-09-07 03:25
Duplicate of #590

**Closed by arkon** 2019-09-07 03:25 UTC
Labels: bug
