### ISSUE TITLE
[Bug] ReadMangaToday : java.lang.Exception: Challenge not found

### ISSUE THREAD

**Issue by Guiorgy** [inorichi/tachiyomi-extensions#2035] opened 2020-01-10 15:37 UTC
### Device information
* Tachiyomi extension version: _1.2.8_
* Tachiyomi version: _r1609_
* Android version: _Fire OS 6.3.0.1 (Android 7.1)_

Anytime I try to update manga or open a chapter on this source I get __java.lang.Exception: Challenge not found__

Open in browser/web view opens the page, but the manga pages (images) seem broken

**Comment by Oopstheresaknifeinmydick** [comment] 2020-01-13 16:14
I am having the same issue. Opening in browser works fine, but opening in web view sometimes opens kissanime without CSS on the website and when I press a chapter all I get either an ad or the page comes up with a bunch of cloudflare loading screens all over the place that after loading usually reveal ads or placeholder icons.

- Extension version: 1.2.9
- App version: 0.8.4
- Andriod version 5.0

**Comment by Guiorgy** [comment] 2020-01-13 16:35
@Oopstheresaknifeinmydick 1.2.9? Which extension are you talking about?

**Comment by Oopstheresaknifeinmydick** [comment] 2020-01-15 07:56
Sorry about that I had the same issue with a different extension and just commented on the wrong thread.

**Comment by arkon** [comment] 2020-01-16 03:25
Duplicate of #2076

**Closed by arkon** 2020-01-16 03:25 UTC
Labels: bug
