### ISSUE TITLE
Hentai2Read search not working

### ISSUE THREAD

**Issue by vkk1903** [inorichi/tachiyomi-extensions#100] opened 2017-08-30 14:12 UTC
Searching after applying category filter don't bring any result. It shows default Manga list ( one that comes after selecting catalogue ) .

Tachiyomi v 0.6 1 - 1208 ( Dev Version ) with Hentai2Read Extension v 1.0.1

**Comment by ddmgy** [comment] 2017-08-30 18:10
Duplicate of #89.

There is a pull request (#90) open that fixes the issues with searching on Hentai2Read, but it has not been merged yet. I'm going through the extension today to find any other things that need to be changed/fixed.

**Closed** 2017-09-23 11:38 UTC
