### ISSUE TITLE
[Bug] <Emerald>: <Java Error when loading/downloading/viewing comic chapters; cannot browse comics in bato.to source>

### ISSUE THREAD

**Issue by Dragoon91786** [inorichi/tachiyomi-extensions#4635] opened 2020-10-19 02:45 UTC
For the past week or more, both the now defunct and the current Emerald extension for Bato.to comics is reporting errors whenever I attempt to load up comics (either through the browse source section, which returns a blank page with an error, or via chapters).

I've attempted multiple workarounds so far, but besides reading the comic in the built-in browser and manually marking off chapters as they have been read, there appears no way to read the bato.to chapters normally.

Unfortunately, I was unable to save screenshots due to a glitch in my Nexus 10's OS.

If someone could take a look at this, I'd greatly appreciate it.

---

## Device information
- Tachiyomi version: 0.10.5
- Android version: 9.0

## Source information
- Name: Christopher M. Vanderwall-Brown [TheDragonLord]
- Extension version: 1.2.2

## Steps to reproduce
1. Uninstalled outdated extension now replaced by Emerald for bato.to website/source.
2. Uninstalled and reinstalled Emerald.
3. Cleared app cache & reformatted cache partition.
4. Restarted system.
5. Removed comic from library and readded it. Cannot search for it via Bato.to repository and it returns error. No change via readding. Comics receive chapter updates and do not report errors when searching for specific comic URLs already saved.
6. Attempted to load up Bato.to page manually to check for CAPTCHA (no CAPTCHA detected) and read comic via web interface. (Comics can be read via web interface.)
7. Attempted to read random comics. (Cannot due to previously stated error on browse source page.)
8. Attempted to test with & without HTTPS option for DDOS protection. (No change.)
9. Tested error on Tachiyomi 0.85 on Android 4.4 app with Emerald 1.2.2 to attempt to replicate error. Error replicated successfully.

†Note: I logged into my bato.to account to see if it had logged me out and I this would fix the problem as sometimes has been reported with the MangaDex app. Did not resolve the issue.

### Expected behavior
Comic chapter should load or give different error. Based upon the error if the extension was being blocked, it shouldn't get chapter updates.

### Actual behavior
Comic chapters cannot load. Comic chapters update when already saved. Comics cannot be browsed in the Emerald extension.

## Other details
Running custom build of Lineage Android 9.0 for Manta (Samsung/Google Nexus 10 tablet, 32 GB).

Have had this issue with other sources (MyReadingManga) when DDOS blocking implemented. However, I have been able to circumvent this via turning off HTTPS for DNS as well as loading the webpage and letting it go through the DDOS protection verification (CAPTCHA). I am logged into the bato.to website with my account. May be efforts to enforce ads on site.

I had a previous issue with the predecessor to the Emerald extension where a bunch of comics randomly lost their authors and were no longer updating, causing errors when updating chapter logs. Previously, this could be fixed by going into the bato.to source and searching for the individual comic and then readding it to my library. Doing so resolved the issue. I do not know the cause for why the error occurred in the first place. Likely, there was some website change that affected the two extensions.

Error has been replicated on Tachiyomi 0.85 on a my Samsung Galaxy Note 2 running Android 4.4 with Emerald 1.2.2. I have not tested it with a previous version of Emerald for comparison.

**Comment by arkon** [comment] 2020-10-19 03:14
Thanks for the detailed issue, but this is a duplicate of #4524.

**Closed by arkon** 2020-10-19 03:14 UTC
Labels: bug

**Comment by Dragoon91786** [comment] 2020-10-19 03:17
Ah, I couldn't find the bug in a search.

 @arkon the error I'm getting is **Value document.domain of type java.lang.string cannot be converted to JSONObject.**
