### ISSUE TITLE
[Bug] Webtoons.com : Throwing java.io.IOException

### ISSUE THREAD

**Issue by pranjalshah9814ps** [inorichi/tachiyomi-extensions#2560] opened 2020-03-31 19:55 UTC
### Device information
* Tachiyomi extension version: 1.2.15
* Tachiyomi version: r1955
* Android version: 10

## Steps to reproduce
1. Open 'Seed' from the Webtoons.com source
2. Try and open Episode 7 Ch 8. (Date is 23/12/18)

### Expected behavior
Open Episode 7 Ch 8. for reding in the viewer

### Actual behavior
Shows a toast that reads "java.io.IOException: Mark invalid"

### Other details
I have seen this behaviour with various chapters from various mange sourced from the Webtoons.com source. Known instances include:
- 'Seed': Ch. 8
- 'CARL': Ch. 11, 17, 31, 32, 34, 41, 49, 54, 58, 66, 68, 87, 91, 95, 98, 105, 107, 119, 132

**Comment by arkon** [comment] 2020-03-31 19:56
Duplicate of #2554

**Closed by arkon** 2020-03-31 19:56 UTC
Labels: bug
