### ISSUE TITLE
[Source Request] Otakusan/Otaku Sanctuary

### ISSUE THREAD

**Issue by imarthurs** [inorichi/tachiyomi-extensions#3028] opened 2020-05-06 02:12 UTC
- Name: Otakusan
- Link: otakusan.net
- Language(s): English

**Comment by SnakeDoc83** [comment] 2020-05-06 02:17
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/1292

**Closed** 2020-05-06 02:19 UTC
Labels: Source Request
