### ISSUE TITLE
Webtoon - Features

### ISSUE THREAD

**Issue by greensad** [inorichi/tachiyomi-extensions#535] opened 2018-10-03 03:19 UTC
This is kind of a tall order but I was wondering if it was possible if webtoon be granted its unique features. These features include, animation, music and multiple translations -including fan translations. I realize these features probably only apply to webtoon but they're part of what makes webtoon special.

**Comment by CarlosEsco** [comment] 2018-10-03 13:07
If the animations are gif.  They are supported in next tachiyomi release.  Music will never be in tachiyomi.  I would have to look at alternate translation to see if its possible to add

**Comment by as280093** [comment] 2019-03-22 14:25
duplicate of #471

**Closed** 2019-03-22 14:31 UTC
