### ISSUE TITLE
[Bug] MangaDex : Global Update Stucked/MangaDex not timing out

### ISSUE THREAD

**Issue by SaruDesu** [inorichi/tachiyomi-extensions#3176] opened 2020-05-16 01:18 UTC
### Device information
- Tachiyomi version: 0.9.2-2289 (standard, 436253dd, 45)
- Android version: 6.0.1 (SDK 23)
- Android build ID: Enigma Port for J2 Prime by ShaDisNX255

### Source information
- Name: MangaDex 
- Extension version: 1.2.90

## Steps to reproduce
1. Add a manga from MangaDex to your library.
2. Try to update library using global update. 

### Expected behavior
It must've updated or timed out. 

### Actual behavior
But it stucks instead. 

### Other details
I did not try this on a clean library with only manga/s from mangadex so maybe you can try to. I will try to recreate the problem in a clean tachiyomi and will update later. 

As you can see It started 08:55 AM and its now 9:00. Yesterday it stucked from 10:00 AM to 2:00 PM until I canceled the update. 
![Screenshot_20200516-091312](https://user-images.githubusercontent.com/51081028/82106756-8d7cc480-9755-11ea-9831-1098f2567fcb.png)

**Comment by arkon** [comment] 2020-05-16 01:19
Duplicate of https://github.com/inorichi/tachiyomi/issues/3137

**Closed by arkon** 2020-05-16 01:19 UTC
Labels: bug
