### ISSUE TITLE
[Source Request] <Gekkou Scan>

### ISSUE THREAD

**Issue by Paulovicbr** [inorichi/tachiyomi-extensions#4595] opened 2020-10-12 20:11 UTC
## Source Website
- Name: Gekkou Scan
- Link: http://leitor.gekkouscans.com.br
- Language(s): Portuguese Brazil

**Comment by CrepeTF** [comment] 2020-10-12 20:13
Dupe of #4458

**Comment by AbdullahM0hamed** [comment] 2020-10-12 20:21
@CrepeTF when I came here to say that and you already beat me to it😔

**Closed** 2020-10-12 20:41 UTC
Labels: Source Request
