### ISSUE TITLE
Source request [Readcomicbooksonline]

### ISSUE THREAD

**Issue by Xmaze12** [inorichi/tachiyomi-extensions#420] opened 2018-07-29 13:35 UTC
https://readcomicbooksonline.org

**Comment by phanirithvij** [comment] 2018-08-02 13:01
[https://readcomiconline.to/](https://readcomiconline.to/)

Is same as kissmaga

**Comment by arkon** [comment] 2018-08-05 05:07
Dupe of #33

**Closed** 2018-08-05 05:44 UTC
