### ISSUE TITLE
[Bug] <mangas.pw>: <no chapters found>

### ISSUE THREAD

**Issue by xXRataXx777** [inorichi/tachiyomi-extensions#4198] opened 2020-08-24 16:42 UTC
## Device information
- Tachiyomi version: 0.10.4
- Android version: 10

## Source information
- Name: My Manga Reader CMS ( Many sources )
- Extension version: 1.2.50

## Steps to reproduce
1.First Step: get into mangas.pw

2.Second Step: touch any manga

### Expected behavior
This should have happened: (that the chapters appear)

### Actual behavior
This happens instead: (error) no chapters found

## Other details

**Comment by SnakeDoc83** [comment] 2020-08-24 17:41
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/4165

**Closed by SnakeDoc83** 2020-08-24 17:41 UTC
Labels: bug

**Comment by xXRataXx777** [comment] 2020-08-24 17:59
> Duplicado de #4165


it's not the same

**Comment by xXRataXx777** [comment] 2020-08-24 18:00
![Screenshot_20200824_125924_eu kanade tachiyomi](https://user-images.githubusercontent.com/69851914/91079424-a5dc6500-e609-11ea-9bd9-f62af9140601.jpg)
![Uploading Screenshot_20200824_125920_eu.kanade.tachiyomi.jpg…]()
is different

**Comment by xXRataXx777** [comment] 2020-08-24 18:01
![Screenshot_20200824_130051_eu kanade tachiyomi](https://user-images.githubusercontent.com/69851914/91079620-e3d98900-e609-11ea-8992-72a41ce8b516.jpg)

**Comment by xXRataXx777** [comment] 2020-08-24 18:04
it had already happened to me
#4160
