### ISSUE TITLE
[Source Request] Word Excerpt

### ISSUE THREAD

**Issue by cievee** [inorichi/tachiyomi-extensions#3228] opened 2020-05-18 17:12 UTC
### Source Website
- Name: Word Excerpt
- Link: https://wordexcerpt.com/
- Language(s): English

### Other Details
Korean Mangas

**Comment by SnakeDoc83** [comment] 2020-05-18 21:02
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/3193

**Closed by SnakeDoc83** 2020-05-18 21:02 UTC
Labels: Source Request
