### ISSUE TITLE
Tachiyomi Bato.to value document.domain to type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by KelaDs** [inorichi/tachiyomi-extensions#4547] opened 2020-10-07 08:20 UTC
## Device information
* Tachiyomi version: 0.10.2
* Android version: 10
* Device: S10 plus

## Source information
* Source name: Bato.to
* Source extension version: Emerald 1.2.2

## Issue/Request 
When I try to open any chapter from this source it won't open and it says "value document.domain to type java.lang.String cannot be converted to JSONObject"

Photo of the Issue 
![Screenshot_20201007-111415_Video Player](https://user-images.githubusercontent.com/72491934/95305146-43c08200-088e-11eb-931c-10e984867667.jpg)

I've cleaned the caches and removed manga from my library and put them back and the problem it's not fixed my phone is updated I even installed the extension again but it still didn't fix anything....

**Comment by scb261** [comment] 2020-10-07 08:22
Duplicate of #4524

**Closed** 2020-10-07 10:42 UTC
