### ISSUE TITLE
[Bug] <EMERALD (bato.to) >: gray box with links when i click on SOME chapters 

### ISSUE THREAD

**Issue by mangalover420** [inorichi/tachiyomi-extensions#4527] opened 2020-10-05 17:23 UTC
## Device information
- Tachiyomi version:  stable 0.10.5
- Android version: 10

## Source information
- Name: ? Emerald(bato.to) 
- Extension version: 1.2.2

## Steps to reproduce
1. when i click on a bato.to chapter but its ONLY the ones updated on 10/4/20 and 10/5/20
2. i checked all the 10/4/20 chapters, and its only the ones i updated in the night

### Expected behavior
This should have happened, bato.to usually works just fine, i read them and this has never happened. 

### Actual behavior
This happens instead![Screenshot_20201005-093455_Tachiyomi.jpg](https://user-images.githubusercontent.com/66030431/95109966-2bb3fb80-06f2-11eb-958f-30b6aa683a98.jpg)

## Other details
i heard there was a problem with the emerald extension, but then i saw there was an update of it, so i installed it and at first it was working fine, the big gray square also doesn't show up with every manga it shows up with some. it only happens with the newer chapters, because when i checked the same source chapters the older ones dont have a problem only the ones that were updated 10/4/20(night) and today 10/5/20.

**Comment by scb261** [comment] 2020-10-05 17:26
Duplicate of #4524

**Closed** 2020-10-05 17:32 UTC
Labels: bug
