### ISSUE TITLE
[SOURCE REQUEST] webcomics app version.

### ISSUE THREAD

**Issue by Mechanical-sanity** [inorichi/tachiyomi-extensions#1301] opened 2019-07-16 11:10 UTC
To my understanding, tachiyomi uses the website version of webcomics? Well, the problem with that is that the website version does not have a complete list of comics, so you can only see so much. Their app version has a complete version of all comics, so is there a way to use the app version? If you check the recently closed issue called "page list empty" you'll see what I'm talking about.

**Comment by arkon** [comment] 2019-07-16 11:36
There isn't an easy way to decompile the app to figure out how to get that data. If you do know the details, that'd be helpful.

**Comment by Mechanical-sanity** [comment] 2019-07-16 12:19
I have no idea, sorry. But is the idea possible?

**Comment by arkon** [comment] 2019-09-07 03:29
Sort of a duplicate of #590

**Closed by arkon** 2019-09-07 03:29 UTC
Labels: Source Request

**Comment by Anutrix** [comment] 2019-12-21 18:59
@arkon https://github.com/CalebFenton/simplify seems to be powerful.
If anyone is interested, they can try reversing with it.
