### ISSUE TITLE
[vietnam] new manga source :hentailx.com

### ISSUE THREAD

**Issue by saiorient** [inorichi/tachiyomi-extensions#718] opened 2019-01-10 01:16 UTC
[https://hentailx.com](https://hentailx.com)

Language: VN-ENG

**Comment by saiorient** [comment] 2019-01-29 01:22
Pliz, help me!

**Comment by arkon** [comment] 2019-03-22 13:03
Duplicate of #630

**Closed by arkon** 2019-03-22 13:03 UTC
Labels: Source Request

**Comment by saiorient** [comment] 2020-01-20 04:17
Please add https://hentailx.com
Thanks
