### ISSUE TITLE
[Bug] WP Manga : Kick me out app (Crashed)

### ISSUE THREAD

**Issue by shipoxx** [inorichi/tachiyomi-extensions#3039] opened 2020-05-06 17:59 UTC
### Device information
- Tachiyomi version: 0.9.0
- Android version: 6.01

### Source information
- Name: mangaswat (WP Ex)
- Extension version:  1.2.8

#other details
• so i installed the extension, and open [mangaswat] in webreview then it's open.. but when i search or add manga to my library, tachiyomi kick me out and he stop work every time.!! I don't know what happened?

**Comment by shipoxx** [comment] 2020-05-06 18:01
![Screenshot_2020-05-06-18-01-20](https://user-images.githubusercontent.com/61906880/81211903-96d29800-8fc3-11ea-9485-5cf46e3e0d50.jpg)

**Comment by shipoxx** [comment] 2020-05-06 18:02
@CarlosEsco

**Comment by arkon** [comment] 2020-05-06 18:03
Duplicate of #2711

**Closed by arkon** 2020-05-06 18:03 UTC
Labels: bug

**Comment by shipoxx** [comment] 2020-05-06 18:06
> Duplicate of #2711

Not working i waiting for loading tum but it's close before!

**Comment by CarlosEsco** [comment] 2020-05-06 18:15
Duplicate means the issue has already been reported.

**Comment by shipoxx** [comment] 2020-05-06 23:08
I know @CarlosEsco 
But what's the solution? ^^
