### ISSUE TITLE
build-in addon

### ISSUE THREAD

**Issue by mged** [inorichi/tachiyomi-extensions#2327] opened 2020-03-01 11:22 UTC
is that possibile? can i bring the extensions internal myself?

the question is, if i make it interanl will it install it as an apk or will it work with out installing it?

**Comment by arkon** [comment] 2020-03-01 14:53
Duplicate of https://github.com/inorichi/tachiyomi/issues/2647

**Closed by arkon** 2020-03-01 14:53 UTC
