### ISSUE TITLE
[Source Request] <Nux Scans>

### ISSUE THREAD

**Issue by ruuno123** [inorichi/tachiyomi-extensions#4630] opened 2020-10-18 11:07 UTC
## Source Website 
- Name: nux scans
- Link: https://nuxscans.blogspot.com/?m=1
- Language(s): english

## Other Details
?

**Comment by scb261** [comment] 2020-10-18 11:10
Duplicate of #4619

**Comment by ruuno123** [comment] 2020-10-18 11:14
Shit....i want to dwnload lot from nux scans...

**Closed** 2020-10-18 13:38 UTC
Labels: Source Request
