### ISSUE TITLE
[Source Request] mangazone.cc source 

### ISSUE THREAD

**Issue by VeganCzech** [inorichi/tachiyomi-extensions#3722] opened 2020-07-08 00:47 UTC
### Source Website
- Name: Mangazone.cc
- Link: https://mangazone.cc/
- Language(s): English 

### Other Details

Thank for adding 🙏😊

**Comment by SnakeDoc83** [comment] 2020-07-08 01:13
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/2622

**Closed by SnakeDoc83** 2020-07-08 01:13 UTC
Labels: Source Request
