### ISSUE TITLE
[Source Request] <manhwamanga.net>

### ISSUE THREAD

**Issue by fawadkhan121** [inorichi/tachiyomi-extensions#4129] opened 2020-08-15 08:00 UTC
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.4)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/
- I will fill out the title and the information in this template

## Source Website
- Name: manhwamanga.net
- Link: https://manhwamanga.net/
- Language(s): english

## Other Details
?

**Comment by fawadkhan121** [comment] 2020-08-15 08:00
There are many new manhwa on this site

**Comment by SnakeDoc83** [comment] 2020-08-15 17:29
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/3136

**Closed by SnakeDoc83** 2020-08-15 17:29 UTC
Labels: Source Request

**Comment by fawadkhan121** [comment] 2020-08-17 08:04
But its Been three months

**Comment by SnakeDoc83** [comment] 2020-08-17 08:12
Doesn't mean you should open another issue.

**Comment by fawadkhan121** [comment] 2020-08-17 08:17
I didn't knew that another request was open sorry though

**Comment by KruxA1** [comment] 2020-10-11 17:55
update on this source please. Thanks!
