### ISSUE TITLE
[Source Request] <Gekkou Scan>

### ISSUE THREAD

**Issue by Paulovicbr** [inorichi/tachiyomi-extensions#4802] opened 2020-11-05 22:14 UTC
## Source Website
- Name: Gekkou Scan
- Link: leitor.gekkouscans.com.br
- Language(s): Portuguese Brazil

**Comment by alessandrojean** [comment] 2020-11-05 23:34
Duplicate of #4458.

**Closed** 2020-11-06 00:04 UTC
Labels: Source Request
