### ISSUE TITLE
[Bug] Japscan:Can't load chapter

### ISSUE THREAD

**Issue by Mitia99** [inorichi/tachiyomi-extensions#3332] opened 2020-05-27 09:03 UTC
### Device information
- Tachiyomi version:stable 0.9.2
- Android version: 9

### Source information
- Name: Japscan
- Extension version: 1.2.20

## Steps to reproduce
1.Open sweet home webtoon
2. Open one chapter
![Screenshot_20200527_120037_eu kanade tachiyomi](https://user-images.githubusercontent.com/56766778/82999687-0e6b7400-a012-11ea-88ee-f437ce738b3f.jpg)

### Expected behavior
Load chapter's images

### Actual behavior
No images.Just retry button

**Comment by SnakeDoc83** [comment] 2020-05-27 09:15
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/2535

**Closed by SnakeDoc83** 2020-05-27 09:15 UTC
Labels: bug
