### ISSUE TITLE
[Source Request] <Niceoppai>

### ISSUE THREAD

**Issue by hightproject** [inorichi/tachiyomi-extensions#3962] opened 2020-08-01 03:36 UTC
### Source Website

- Name: Niceoppai
- Link: http://www.niceoppai.net/
- Language(s): TH

**Comment by SnakeDoc83** [comment] 2020-08-01 04:34
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/1109

**Closed by SnakeDoc83** 2020-08-01 04:34 UTC
Labels: Source Request
