### ISSUE TITLE
[Source Request] SkyFall Scans

### ISSUE THREAD

**Issue by sam7028** [inorichi/tachiyomi-extensions#4173] opened 2020-08-20 05:18 UTC
**Source Website**

- Name : SkyFall Scans

- Link : https://skyfallscans.ga

- Language(s): English

**Comment by SnakeDoc83** [comment] 2020-08-20 05:41
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/2276

**Closed by SnakeDoc83** 2020-08-20 05:41 UTC
Labels: Source Request
