### ISSUE TITLE
Request new extension

### ISSUE THREAD

**Issue by 1min33sec** [inorichi/tachiyomi-extensions#3520] opened 2020-06-13 14:30 UTC
### Device information
* Tachiyomij2k version: 1.0.7
* Android version: 10
* Device: SM-A505F

## Issue/Request
Please add this extension
[WebNovel](https://m.webnovel.com/)

**Comment by SnakeDoc83** [comment] 2020-06-13 17:26
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/1350

**Closed by SnakeDoc83** 2020-06-13 17:26 UTC
