### ISSUE TITLE
Missing manga in catalogue manga rock source

### ISSUE THREAD

**Issue by ben71504** [inorichi/tachiyomi-extensions#1205] opened 2019-06-16 15:27 UTC
Manga seems to be missing in the catalogue even though it's in the manga rock app, so for example Tokyo ghoul and one piece are in the app but they are not in the catalogue. If they something wrong?

**Comment by arkon** [comment] 2019-06-16 15:29
Duplicate of #1199

**Closed by arkon** 2019-06-16 15:29 UTC
