### ISSUE TITLE
[Source Request] <18comic>

### ISSUE THREAD

**Issue by XeroxV** [inorichi/tachiyomi-extensions#4005] opened 2020-08-04 07:16 UTC
Source Website
 Name: 18comic
 Link: https://18comic.vip/
 Language(s): Chinese / Japanese

Other Details
Alternate website : https://18comic.org/

This site has lots of doujins ( chinese/japanese ), manhwas from Toptoon.net, Toomics, Lezhin. It's a really good site for 18+ stuffs.

**Comment by SnakeDoc83** [comment] 2020-08-04 07:18
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/3598

**Closed by SnakeDoc83** 2020-08-04 07:18 UTC
Labels: Source Request
