### ISSUE TITLE
[Bug] mangakalot in mangabox: did not find balanced marker at 'status' 

### ISSUE THREAD

**Issue by Seishirou101** [inorichi/tachiyomi-extensions#1727] opened 2019-11-01 01:16 UTC
### Device information
* Tachiyomi extension version: 1. 2. 1
* Tachiyomi version: v8.4.5-EH
* Android version: 9

## Steps to reproduce
1. Go into mangakalot extension
2. Go to any Manga listing 

### Expected behavior
Manga updates with cover/synopsis/etc

### Actual behavior
Error pops up and it stays blank

### Other details
Attempted after transition from stand alone mangakalot to mangabox one

**Comment by joseph619** [comment] 2019-11-01 01:40
Duplicate of #1726 , please close

**Closed** 2019-11-01 01:51 UTC
Labels: bug
