### ISSUE TITLE
Newtoki Webtoon Chapter Problem

### ISSUE THREAD

**Issue by JudiciousVick** [inorichi/tachiyomi-extensions#3879] opened 2020-07-23 20:08 UTC
### Device information
- Tachiyomi version: 0.9.2-2543
- Android version: 9

### Source information
- Name: Newtoki Webtoon 
- Extension version: 1.2.11 

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
It should load the chapter that were selected

### Actual behavior
Recently when i open newtoki and click on one of the manga it show some other manga and it never changes same manga same chapter in any other manga i open. see the images

### Other details
![Screenshot_20200724-013245](https://user-images.githubusercontent.com/59502042/88333699-4c54f200-cd4e-11ea-9783-1c6974b13ff4.jpg)
![Screenshot_20200724-013306](https://user-images.githubusercontent.com/59502042/88333710-4f4fe280-cd4e-11ea-90b9-485614b50944.jpg)

**Comment by arkon** [comment] 2020-07-23 20:37
Duplicate of #3794

**Closed by arkon** 2020-07-23 20:37 UTC
Labels: bug
