### ISSUE TITLE
[Source Request]JPManga

### ISSUE THREAD

**Issue by ziovelion** [inorichi/tachiyomi-extensions#3338] opened 2020-05-27 20:18 UTC
Name: JPManga
Link: http://www.jpmanga.com
Language(s): english and raw

**Comment by SnakeDoc83** [comment] 2020-05-27 23:30
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/3256

**Closed by SnakeDoc83** 2020-05-27 23:30 UTC
Labels: Source Request
