### ISSUE TITLE
Mangaae is missing categories filter 

### ISSUE THREAD

**Issue by mged** [inorichi/tachiyomi-extensions#2533] opened 2020-03-28 19:57 UTC
mangaae has only filter of author and release date and chapter count/amount 

but we can not filter by categories like action romance hentai school lfe slie of life drama etc etc

their website has this ability but the extenion has not it please add it

**Comment by arkon** [comment] 2020-03-28 19:59
Duplicate of #2494. You can try adding it, since you said you have developer experience.

**Comment by mged** [comment] 2020-03-28 19:59
can i add it?

how?!?!?!?!?!?!!?!? if i can add it i would be happy to try!

**Closed by arkon** 2020-03-28 19:59 UTC
Labels: enhancement

**Comment by mged** [comment] 2020-03-28 20:00
i will trt to add it in my free time, who i contact for this? i cant talk u in discord you seem to be disabled DMs? i dont know i cant DM u for some reason.

**Comment by arkon** [comment] 2020-03-28 20:00
> how?!?!?!?!?!?!!?!? 

https://github.com/inorichi/tachiyomi-extensions/blob/master/CONTRIBUTING.md

Use existing extensions as code references.
