### ISSUE TITLE
[Feature Request] Mangadex: Hide duplicate chapters from multiple sources/translations

### ISSUE THREAD

**Issue by Dangelman** [inorichi/tachiyomi-extensions#3764] opened 2020-07-11 20:59 UTC
I'd be nice to be able to hide same chapters from multiple sources.
For example, [One Punch Man](https://mangadex.org/title/7139/one-punch-man) has currently two English translations on Mangadex. This is annoying, especially when reading, because you always have to jump one chapter.
Sorting by Source/Chapter number in the options doesn't change anything for me.

So I'm suggesting to add a toggeable option in the filters to hide certain sources.

![OPM](https://user-images.githubusercontent.com/26676154/87233640-8bd42380-c3c9-11ea-9030-9cb9c824e162.jpg)

**Comment by arkon** [comment] 2020-07-11 21:16
Duplicate of https://github.com/inorichi/tachiyomi/issues/969

**Closed by arkon** 2020-07-11 21:16 UTC
Labels: enhancement
