### ISSUE TITLE
[Bug] HTTP error 403 on Kissmanga extension

### ISSUE THREAD

**Issue by Degenerate6975** [inorichi/tachiyomi-extensions#1768] opened 2019-11-12 02:27 UTC
### Device information
* Tachiyomi extension version: 1.2.9
* Tachiyomi version: 0.8.4

## Steps to reproduce
1. attempt to open anything related to the kissmanga extension 

### Expected behavior
Open anything related to the kissmanga Tachiyomi extension 

### Actual behavior
Http error 403 message appears 

### Other details
N/A

**Comment by arkon** [comment] 2019-11-12 02:30
Seems to work fine for me. Does changing to a different network (wifi, data, VPN, etc) make any difference?

**Comment by Degenerate6975** [comment] 2019-11-12 02:44
No still having the issue

**Comment by bellberry** [comment] 2019-11-12 03:08
I have this issue too!  When I opened the manga in web view, it prompted a CAPTCHA.  Once I completed those, I was able to read the manga in the app, but it didn't seem to stick -- about an hour later after being away from the app, the error reappeared and I had to do the CAPTCHAs again.  I hope this helps.

![Screenshot_20191111-210106](https://user-images.githubusercontent.com/56645444/68638439-30166b00-04c7-11ea-846c-a0094191bb60.png)
![Screenshot_20191111-210323](https://user-images.githubusercontent.com/56645444/68638446-360c4c00-04c7-11ea-899c-9cf5beb7d5e7.png)

**Comment by Degenerate6975** [comment] 2019-11-12 03:16
> I have this issue too! When I opened the manga in web view, it prompted a CAPTCHA. Once I completed those, I was able to read the manga in the app, but it didn't seem to stick -- about an hour later after being away from the app, the error reappeared and I had to do the CAPTCHAs again. I hope this helps.
> 
> ![Screenshot_20191111-210106](https://user-images.githubusercontent.com/56645444/68638439-30166b00-04c7-11ea-846c-a0094191bb60.png)
> ![Screenshot_20191111-210323](https://user-images.githubusercontent.com/56645444/68638446-360c4c00-04c7-11ea-899c-9cf5beb7d5e7.png)

Although it still won't let me use it in the app this could be what's causing the issue

**Comment by CuZnDragon** [comment] 2019-11-12 17:45
Using the dev version and have the same issue.

**Comment by jimm0thy** [comment] 2019-11-13 14:37
I'm also getting the same error. The captcha showed up for me once in webview but made no difference in the app. Unable to load anything related to kissmanga in the app now

**Comment by QuietusWolfe** [comment] 2019-11-13 17:51
Same problem. 
0.8.4 version of the app and current version of the extension.
Kissmanga loads fine in a browser, but not via the app.

**Comment by sutatss** [comment] 2019-11-13 18:37
Same for me as well.
Android
version 0.8.4 
Current version of Kissmanga extension
cleared all cache
Only get the 403 with Kissmanga - the rest of the catalogs work fine.

**Comment by SBKillerDram** [comment] 2019-11-13 23:12
I am also receiving this error. I was reading a chapter then when i went to go to the next chapter it gave me the error and i have tried clearing cache and making sure everything is updated. I can load the website on my phone perfectly fine and dont need to do any captchas.

**Comment by hopt28** [comment] 2019-11-14 04:06
Also having this problem since yesterday.

**Comment by Sailanarmo** [comment] 2019-11-14 15:56
Can confirm that I have been having the same issue for a couple of days now.

**Comment by KingsleyBawuah** [comment] 2019-11-14 16:35
Same here, completing the captcha in webview seems to help for a bit

**Comment by GuyInDogSuit** [comment] 2019-11-14 16:51
Same, just realized this was happening today as I normally manually download my chapters and thought something was off about some of my sources.

**Comment by kkhan01** [comment] 2019-11-14 19:16
Completing the webview captcha (assuming by webview you mean any old browser... unless there's a Tachiyomi feature I don't know about) doesn't allow the app to pull from the extension for me :man_shrugging:

**Comment by MerradOklom** [comment] 2019-11-14 20:22
> Completing the webview captcha (assuming by webview you mean any old browser... unless there's a Tachiyomi feature I don't know about) doesn't allow the app to pull from the extension for me

You can open in web view either from the Info tab of your manga (right) or in Browse (left) if you're using the dev build:
![Photo_20191114_171230](https://user-images.githubusercontent.com/43864503/68893032-0d709600-0703-11ea-8274-7e924e8d66e3.jpg)
Sorry for the bad quality of the image

**Comment by integralLeft** [comment] 2019-11-14 21:18
I've been getting this error for days now. Any idea when it's going to be resolved?

**Comment by Monkeyfan727** [comment] 2019-11-16 08:57
The way I stumbled into a fix was using the web view function on a kiss Manga title I was reading and then backing out and updating my library don't know if this will fix for others but has solved my connection issues and I've them for a week approximately

**Comment by Monkeyfan727** [comment] 2019-11-17 22:11
I'm doing my trick in the previous post multiple times a day but it is a temporary fix till the issue gets solved

**Comment by happywillow0** [comment] 2019-11-19 02:54
I'm not sure how long it is going to last but I think KissManga finally lowered the protection to the automatic checking level.

**Comment by SnakeDoc83** [comment] 2020-01-08 07:04
@arkon Including this pinned issue, there are 6 open issues on Kissmanga.  I don't know how aggressively you want to pare them down, but I don't think they all need to be open.  It seems to me that most were temporary issues caused by Kissmanga occasionally being more aggressive with their cloudflare protection/captchas.

https://github.com/inorichi/tachiyomi-extensions/issues/1818
https://github.com/inorichi/tachiyomi-extensions/issues/1021
https://github.com/inorichi/tachiyomi-extensions/issues/983
https://github.com/inorichi/tachiyomi-extensions/issues/872 (This one might be worth preserving, but it's a bit old and I wouldn't know what to do with it.)
https://github.com/inorichi/tachiyomi-extensions/issues/258

**Comment by asdkant** [comment] 2020-01-12 22:34
Since opening the site with the web view and logging in worked for mangadex in the past, I tried to do the same with kissmanga. the issue is that the web view fails to load something from the page (the CSS I think), and I can't see the login link, so I can't reach the login page (`https://kissmanga.com/Login`).

Is there any way to be able to open arbitrary URLs with the web view?

**Comment by AsunaKai** [comment] 2020-01-27 17:55
![Screenshot_20200127-125021_Samsung Internet](https://user-images.githubusercontent.com/59960660/73199917-c7bd4a00-4103-11ea-9957-f1b3428edf17.jpg)
![Screenshot_20200127-125025_Samsung Internet](https://user-images.githubusercontent.com/59960660/73199924-cd1a9480-4103-11ea-9b57-0bca1bb74cc4.jpg)
Ive had this 403 error issue, id usually try to refresh after deleting my browser history but for whatever reason today i cant gain access to the site at all. Is there a new website  change if so if possible may i get a link please and is this 403 error just temporary because i was just reading manga fine a few days ago with no issues.

**Comment by an94baller** [comment] 2020-02-13 10:02
> 
> 
> Since opening the site with the web view and logging in worked for mangadex in the past, I tried to do the same with kissmanga. the issue is that the web view fails to load something from the page (the CSS I think), and I can't see the login link, so I can't reach the login page (`https://kissmanga.com/Login`).
> 
> Is there any way to be able to open arbitrary URLs with the web view? Alternatively, it'd be nice to have a way to directly open the login page of a given supported site.

does logging in actually fix the search issue? seeing as you don't need an account to browse/search/advanced-search on the site

I had bookmarked several manga from this website before the extension borked, those can still be downloaded/updated weirdly enough

**Comment by asdkant** [comment] 2020-02-13 13:16
As far as I recall, when I trierd with a browser logging in stopped cloudflare from re-checking every time I tried to do anything on the site. The cloudflare thing seems to be what's borking tachiyomi.

Alternatively, some way to stop cloudflare checks from borking tachiyomi in general would be good too (but I don't know how to go about implementing that)

**Comment by an94baller** [comment] 2020-02-13 22:29
> 
> 
> As far as I recall, when I trierd with a browser logging in stopped cloudflare from re-checking every time I tried to do anything on the site. The cloudflare thing seems to be what's borking tachiyomi.
> 
> Alternatively, some way to stop cloudflare checks from borking tachiyomi in general would be good too (but I don't know how to go about implementing that)

kinda weird that it can still fetch and DL existing added manga tho, maybe add a manual kissmanga url option to subscribe to titles?




does the extension not cache cookies or something? similar to how kissmanga extension keeps cookies pertaining to login details maybe this one can be modified to store short-term cloudflare ones that says device passes check? @inorichi

**Comment by arkon** [comment] 2020-02-13 22:52
The app already handles CloudFlare to some extent, otherwise Kissmanga wouldn't work at all.

**Comment by arkon** [comment] 2020-03-09 18:29
Newer Tachiyomi versions should be able to handle it a bit better. Closing this for now.

**Closed by arkon** 2020-03-09 18:29 UTC
Labels: bug

**Comment by patrickhgb** [comment] 2020-03-10 10:34
> 
> 
> Newer Tachiyomi versions should be able to handle it a bit better. Closing this for now.

what changed exactly

**Comment by Hongsworth** [comment] 2020-03-24 18:42
I have the latest version of tachiyomi (0.8.5) but is still getting this issue, is there a fix to this?

**Comment by CarlosEsco** [comment] 2020-03-24 18:44
@Hongsworth https://github.com/inorichi/tachiyomi-extensions/issues/2496
