### ISSUE TITLE
[Source Request] <gmanga>

### ISSUE THREAD

**Issue by iham15** [inorichi/tachiyomi-extensions#3664] opened 2020-07-01 10:06 UTC
### Source Website
- Name: gmanga
- Link: www.gmanga.me
- Language(s): arabic

**Comment by SnakeDoc83** [comment] 2020-07-01 10:07
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/117

**Closed by SnakeDoc83** 2020-07-01 10:07 UTC
Labels: Source Request
