### ISSUE TITLE
[Source Request] LOLScans

### ISSUE THREAD

**Issue by NightA** [inorichi/tachiyomi-extensions#740] opened 2019-01-23 08:30 UTC
This is the official reader used by the LOLScans scanlation group: https://forums.lolscans.com/book/r.php
It's updated more frequently than the aggregator sites they use and could be nice to have as a source.

**Comment by arkon** [comment] 2019-09-07 03:30
Duplicate of #1337

**Closed by arkon** 2019-09-07 03:30 UTC
Labels: Source Request
