### ISSUE TITLE
[Bug] MangaSwat in Madara : MangaSwat doesn't work !!

### ISSUE THREAD

**Issue by dzotaku66** [inorichi/tachiyomi-extensions#2917] opened 2020-04-28 22:21 UTC
#2509 # Other details
When I open MangaSwat source , it says "this website is secured"
And when I try open in webview , it kick me out the app .
What's the solution ??

**Comment by SnakeDoc83** [comment] 2020-04-29 02:48
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/2711

**Closed** 2020-04-29 02:49 UTC
Labels: bug
