### ISSUE TITLE
[Bug] Neox Scanlator in madara extension

### ISSUE THREAD

**Issue by fabriciobusiness** [inorichi/tachiyomi-extensions#4522] opened 2020-10-05 13:00 UTC
Good Morning,
Neox Scanlator changed its domain from neoxscan.com to neoxscan.net
and because of that the sleeves are not opening.

**Comment by arkon** [comment] 2020-10-05 13:08
Duplicate of #4523

**Closed by arkon** 2020-10-05 13:08 UTC
Labels: bug
