### ISSUE TITLE
[Source Request Arabic] <mad scientistss>

### ISSUE THREAD

**Issue by mohalimoh14** [inorichi/tachiyomi-extensions#3817] opened 2020-07-17 11:32 UTC
- Name: mad scientistss
- Link: https://mad-scientistss.blogspot.com
- Language(s): Arabic

**Comment by SnakeDoc83** [comment] 2020-07-18 09:05
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/2635

**Closed by SnakeDoc83** 2020-07-18 09:05 UTC
Labels: Source Request
