### ISSUE TITLE
[Source Request] [INDONESIA] Source Name sektekomik

### ISSUE THREAD

**Issue by emyrulzul** [inorichi/tachiyomi-extensions#1666] opened 2019-10-18 01:15 UTC
### Source Website
The website for this source can be found [here](website_url).
https://sektekomik.com/

**Comment by emyrulzul** [comment] 2019-10-18 02:15
bro please add sektekomik

**Comment by arkon** [comment] 2019-10-18 02:33
Duplicate of #1664. Do you really think spamming will get it added faster?

**Closed by arkon** 2019-10-18 02:33 UTC
Labels: Source Request
