### ISSUE TITLE
Mangatensei - Source

### ISSUE THREAD

**Issue by Ozs000** [inorichi/tachiyomi-extensions#1253] opened 2019-07-03 18:30 UTC
https://mangatensei.com/

Adding the tags would also be much aprecciated.
https://mangatensei.com/browse

**Comment by MerradOklom** [comment] 2019-07-04 02:08
Apparently this is a duplicate of #1078

**Comment by Ozs000** [comment] 2019-07-04 02:10
Gotcha closin it down

**Closed** 2019-07-04 02:10 UTC
