### ISSUE TITLE
[Source request] mad scientistss

### ISSUE THREAD

**Issue by RukunSama** [inorichi/tachiyomi-extensions#3864] opened 2020-07-21 12:09 UTC
Mad scientistss
Link: https://mad-scientistss.blogspot.com/
Lang: arabic

**Comment by SnakeDoc83** [comment] 2020-07-21 17:53
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/2635

**Closed by SnakeDoc83** 2020-07-21 17:53 UTC
