### ISSUE TITLE
Webcomics error (page list is empty)

### ISSUE THREAD

**Issue by Znova99** [inorichi/tachiyomi-extensions#1180] opened 2019-06-09 22:08 UTC
BUGS:
  Titles in webcomics shows page list is empty

App version:0.8.4
Source version :1.2.1

**Comment by shaishaiNg** [comment] 2019-07-05 06:43
i think that's coz the chapter is paid

**Comment by ZaneHannanAU** [comment] 2019-07-05 10:53
WebComics only allows certain chapters to be viewed over the web ui. Further chapters are accessible via the proprietary application they distribute via google play. You can reverse engineer the application through various means; but would be arduous to perform.

**Comment by arkon** [comment] 2019-09-07 03:21
Duplicate of #1298

**Closed by arkon** 2019-09-07 03:21 UTC
