### ISSUE TITLE
Mangarock.es extension

### ISSUE THREAD

**Issue by EmmaKhan3** [inorichi/tachiyomi-extensions#3101] opened 2020-05-10 14:09 UTC
---

### Device information
* Tachiyomi version: v0.9.2
* Android version: 8.1
* Device: Itel

### Source information
* Source name:
* Source extension version: 

## Steps to reproduce
1. First step
2. Second step

## Issue/Request
Mangarock.es extension request

**Comment by arkon** [comment] 2020-05-10 14:10
Duplicate of #2710

**Closed by arkon** 2020-05-10 14:10 UTC
