### ISSUE TITLE
[Source Request] www.mangabz.com

### ISSUE THREAD

**Issue by hanxin1997** [inorichi/tachiyomi-extensions#2592] opened 2020-04-05 05:57 UTC
### Source Website
Website can be found at <http://www.mangabz.com/>.

### Other Details
Chinese website

**Comment by SnakeDoc83** [comment] 2020-04-05 07:21
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/1887

**Closed** 2020-04-05 12:59 UTC
Labels: Source Request
