### ISSUE TITLE
Mangakakalot

### ISSUE THREAD

**Issue by grrlss** [inorichi/tachiyomi-extensions#435] opened 2018-08-05 11:17 UTC
http://mangakakalot.com/

This is a good site for manga. I hope you can add this. Thanks in advance

**Comment by joseph619** [comment] 2018-08-05 11:59
I agree as well. Aming my top 4 manga sites.

**Comment by arkon** [comment] 2018-08-05 15:06
Dupe of #111

**Closed** 2018-08-05 15:11 UTC
