### ISSUE TITLE
[Bug] <PMScans:madara>: <the source pmscans gives (http error 400)>

### ISSUE THREAD

**Issue by zimakkkk** [inorichi/tachiyomi-extensions#4934] opened 2020-11-23 17:37 UTC
## Device information
- Tachiyomi version: 0.10.5
- Android version: 8.0

## Source information
- Name: pmscans
- Extension version: 1.2.150

**Comment by Riztard** [comment] 2020-11-24 05:36
Duplicate of #4830

**Closed** 2020-11-24 13:30 UTC
Labels: bug
