### ISSUE TITLE
[Source Request] Kumanga

### ISSUE THREAD

**Issue by leox233** [inorichi/tachiyomi-extensions#3304] opened 2020-05-24 23:52 UTC
Name: kumanga
Link:https://https://www.kumanga.com/mangalist?&page=1
Language(s): Spanish

**Comment by SnakeDoc83** [comment] 2020-05-24 23:52
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/921

Search before you make more requests.

**Closed by SnakeDoc83** 2020-05-24 23:52 UTC
Labels: Source Request
