### ISSUE TITLE
[Source Request] <Timelessleaf>

### ISSUE THREAD

**Issue by Mizora15** [inorichi/tachiyomi-extensions#3538] opened 2020-06-15 12:15 UTC
### Source Website
- Name: Timelessleaf
- Link: https://timelessleaf.com/
- Language(s): English

### Other Details
It's a great scanlation with lots of updates

**Comment by arkon** [comment] 2020-06-15 13:01
Duplicate of #2251

**Closed by arkon** 2020-06-15 13:01 UTC
Labels: Source Request
