### ISSUE TITLE
Tencent Comics (腾讯动漫)

### ISSUE THREAD

**Issue by XeroxV** [inorichi/tachiyomi-extensions#4204] opened 2020-08-25 09:51 UTC
Source Website
- Name: Tencent Comics (腾讯动漫)
- Link: https://ac.qq.com/
- Language(s): Chinese

Other Details
It's an official site for manhua and manga. Some require coins to read them but there are also free to read manhua as well

**Comment by SnakeDoc83** [comment] 2020-08-25 17:34
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/412

**Closed by SnakeDoc83** 2020-08-25 17:34 UTC
Labels: Source Request
