### ISSUE TITLE
[Source Request] [18+] H-browser

### ISSUE THREAD

**Issue by Jumpgang** [inorichi/tachiyomi-extensions#1802] opened 2019-11-20 05:57 UTC
### Source Website:
Hbrowse.com

### Other Details
Great Doujin site with multiple chapter Doujins all grouped together, instead of each chapter being treated as a separate book.

**Comment by SnakeDoc83** [comment] 2019-11-20 06:39
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/1174

**Comment by Jumpgang** [comment] 2019-11-20 07:01
It was previously closed, I am trying to bring it to attention once again

**Comment by arkon** [comment] 2019-11-20 12:19
It's not closed. Don't create duplicates

**Closed by arkon** 2019-11-20 12:19 UTC
Labels: Source Request
