### ISSUE TITLE
[Bug] <mangas.pw>: <no chapters found>

### ISSUE THREAD

**Issue by xXRataXx777** [inorichi/tachiyomi-extensions#4199] opened 2020-08-24 21:55 UTC
## Device information
- Tachiyomi version: 0.10.4
- Android version: 10

## Source information
- Name: My Manga Reader CMS ( Many sources )
- Extension version: 1.2.50

## Steps to reproduce
1. First Step get into mangas.pw (in recent no)

2. Second Step touch any manga

### Expected behavior
This should have happened 
(that the chapters appear)

### Actual behavior
This happens instead
(error) no chapters found

## Other details

¡Not Duplicate of # 4165!

![Screenshot_20200824_165004](https://user-images.githubusercontent.com/69851914/91099974-ecda5280-e629-11ea-8074-05b25e9c8367.jpg)
![Screenshot_20200824_165011_eu kanade tachiyomi](https://user-images.githubusercontent.com/69851914/91100004-fa8fd800-e629-11ea-8de1-5f7ec642324f.jpg)
![Screenshot_20200824_165234](https://user-images.githubusercontent.com/69851914/91100121-3aef5600-e62a-11ea-870f-fe0ea7c21d47.jpg)

**Comment by arkon** [comment] 2020-08-24 22:07
Stop opening duplicate tickets.

Duplicate of #4165

**Closed by arkon** 2020-08-24 22:07 UTC
Labels: bug
