### ISSUE TITLE
FoolSlide Hentai Cafe not working

### ISSUE THREAD

**Issue by Tsagu** [inorichi/tachiyomi-extensions#1397] opened 2019-08-17 06:08 UTC
Hentai Cafe in the FoolSlide extension throwing out "Invoke virtual method "java.lang.String org.jsoup.nodes.Elem..."

Not loading at all.

Using Tachiyomi v0.8.4

**Comment by happywillow0** [comment] 2019-08-25 06:13
Have you had a chance to try again? 

I'm just loaded up foolslide 1.2.23 on the dev r1521 and hentai cafe looks to be working normally. 

Any steps to reproduce if you are still having the issue?

**Comment by rama982** [comment] 2019-08-25 11:58
This issue must be closed, its clear his internet provider is blocking him from accessing the website.

**Comment by ZaneHannanAU** [comment] 2019-08-25 12:04
@Tsagu can you test after installing and setting up https://one.one.one.one, please? It may be inaccessible due to your internet provider and DNS.

**Comment by joseph619** [comment] 2019-08-26 03:15
@arkon  Please close this, Hentai Cafe works fine and this is not a Tachiyomi issue

**Closed** 2019-08-26 11:19 UTC
