### ISSUE TITLE
[source request] mangatoon

### ISSUE THREAD

**Issue by Mechanical-sanity** [inorichi/tachiyomi-extensions#1312] opened 2019-07-19 01:30 UTC
Can you add mangatoon? And while your at it, can you make the extensions list in alphabetical order?

**Comment by SnakeDoc83** [comment] 2019-07-19 02:01
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/697

**Closed** 2019-07-19 02:40 UTC
