### ISSUE TITLE
[Bug] <Mangahasu>: <Unable to load any chapter. Error: For input string: "">

### ISSUE THREAD

**Issue by brazor421** [inorichi/tachiyomi-extensions#4878] opened 2020-11-14 14:07 UTC
## Device information
- Tachiyomi version: 0.10.5-2807
- Android version: 9

## Source information
- Name: Mangahasu
- Extension version: 1.2.8

## Steps to reproduce
1. Choose any manga
2. Try to read any chapter

### Expected behavior
Chapter opens without any issues

### Actual behavior
Unable to open a chapter; For input string: "" pops up.

## Other details
![Screenshot_2020-11-14-17-53-11-725_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/74458684/99148900-f06afc00-26a3-11eb-934b-26dde41b1d7e.jpg)

**Comment by scb261** [comment] 2020-11-14 14:20
Duplicate of #3942.

But I can't reproduce it, maybe try to [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/).

**Closed** 2020-11-14 15:06 UTC
Labels: bug
