### ISSUE TITLE
[Source Request] <littlexgarden>

### ISSUE THREAD

**Issue by N0N031** [inorichi/tachiyomi-extensions#4632] opened 2020-10-18 16:21 UTC
Source Website
- Name: littlexgarden
- Link: https://littlexgarden.com/one-piece
- Language(s): French

Other Details : 
Mangas Full Color

**Comment by scb261** [comment] 2020-10-18 16:25
Duplicate of #4251

**Closed** 2020-10-18 17:38 UTC
Labels: Source Request
