### ISSUE TITLE
Union Mangas not working

### ISSUE THREAD

**Issue by gabrielmartt** [inorichi/tachiyomi-extensions#392] opened 2018-07-09 02:54 UTC
Union mangas, portuguese source not working

loading forever and error 504 appears

sorry about my english

Tachiyomi 7.4
union mangas 1.2.2

**Comment by masgritz** [comment] 2018-07-12 01:48
The extension is fine, I even double checked for any changes in the structure (in case it needs to be updated) but the problem is their website itself.

Go to their http://unionmangas.site/ (if it's not down at the moment) and you'll see a message stating that they're going through a server maintenance:

"Atenção! Estamos realizando uma manutenção no servidor, por isso está ocorrendo toda essa instabilidade. Avisaremos quando terminar."

**Comment by CarlosEsco** [comment] 2018-07-12 16:06
closing as its not a tachiyomi issue

**Closed by CarlosEsco** 2018-07-12 16:06 UTC

**Comment by masgritz** [comment] 2018-07-13 03:01
Just to add, Union Mangas has finished their server maintenance a few hours ago. Everything is back to normal.
