### ISSUE TITLE
[Bug] Duplicate favorites

### ISSUE THREAD

**Issue by mrdroops** [inorichi/tachiyomi-extensions#2583] opened 2020-04-04 00:47 UTC
### Device information
* Tachiyomi extension version: 1.2.7
* Tachiyomi version: 0.8.5
* Android version: 9

## Steps to reproduce
1. First Step
Open the MangaHost extension, add any manga in the "Latest" tab.

2. Second Step
Exit the extension or application as you prefer, and reopen the extension in "Latest" and the manga just added to the library will no longer appear as if it had been added.

### Expected behavior
When adding to favorites, make it explicit that it is already in the library.

### Actual behavior
When I add a manga to my favorites, it appears that it was added correctly, but when I leave the application or go to my library and go back to the extension with the problem, it no longer appears as if it had already been added.

**Comment by alessandrojean** [comment] 2020-04-04 03:58
I will take a look and try to fix it, probably they changed the url structure in the latest page.

**Comment by alessandrojean** [comment] 2020-04-04 14:41
I am not able to reproduce the issue, I tried now but everything is working as expected, the recent mangas that I added to my library are marked as they are in the library on the recents when I reopen then.

**Closed** 2020-04-13 21:25 UTC
Labels: bug
