### ISSUE TITLE
[Bug] Readmanga : failed to decode image

### ISSUE THREAD

**Issue by VeryBadKiwi** [inorichi/tachiyomi-extensions#2303] opened 2020-02-27 18:17 UTC
### Device information
* Tachiyomi extension version: 1.2.17
* Tachiyomi version: r1771 (0f2d4800)
* Android version: 10

## Steps to reproduce
1. Pick manga from Readmanga repository
2. Start reading

### Expected behavior
Manga will load pages to read

### Actual behavior
Writes that it was not possible to decode the image

### Other details
-

**Comment by arkon** [comment] 2020-02-27 19:57
Duplicate of #2300

**Closed by arkon** 2020-02-27 19:57 UTC
Labels: bug
