### ISSUE TITLE
[Bug] HTTP Error 403

### ISSUE THREAD

**Issue by Shweeisme** [inorichi/tachiyomi-extensions#1771] opened 2019-11-12 06:09 UTC
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

Everytime I try to open a chapter to read in any manga from any extension, a HTTP error 403 pops ups. I already tried clearing the cache, checking for updates in the app and extensions. Is it a wifi problem, because my wifi seems to be working fine for.everything else. I need help fixing this.

**Comment by happywillow0** [comment] 2019-11-13 04:35
Which extension are you referring to? 

403 is normally the http Forbidden code but comes from a specific server which in this case relates to a specific extension and site.

**Comment by hopt28** [comment] 2019-11-14 04:06
@happywillow0 This is happening to me on Kissmanga specifically. I don't really use other extensions, so I wouldn't know about them.

**Comment by happywillow0** [comment] 2019-11-14 04:55
Kissmanga has increased their security. 
You will have to use webview solve the captcha when the site requires you to. You can either find webview [from an existing manga](https://tachiyomi.org/help/faq/extensions/#some-common-errors-you-might-encounter) or from the extension page if you are using the dev version. 

Duplicate of #1768

**Closed** 2019-11-14 12:23 UTC
Labels: bug

**Comment by Slide123** [comment] 2021-03-08 19:12
Je recois aussi ce message je veux savoir pourquoi et meme mangakalot a commencé a déranger depuis que c'est message son apparu les site comme mangatx, manhuaus, comickiba et bien d'autre me lance cette erreur
