### ISSUE TITLE
[ARABIC source] <gmanga>

### ISSUE THREAD

**Issue by REDAKUN** [inorichi/tachiyomi-extensions#4331] opened 2020-09-07 16:50 UTC
--

## Source Website
- Name: gmanga
- Link: https://gmanga.me/
- Language(s): ARABIC

## Other Details
THE BEST ARABIC MANGA WEBSITE FOR SURE

**Comment by arkon** [comment] 2020-09-07 16:54
DUPLICATE OF #117

**Closed by arkon** 2020-09-07 16:54 UTC
Labels: Source Request
