### ISSUE TITLE
Mangago Obfuscation 

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi-extensions#434] opened 2018-08-05 10:11 UTC
It seems Mangago isn't working anymore again. I have cleared the cache and cookies. None of the chapters/cover load for any manga. 

Mangago version: 1.2.5

Tachiyomi version: 0.7.4

**Comment by arkon** [comment] 2019-03-22 12:58
Duplicate of #377

**Closed by arkon** 2019-03-22 12:58 UTC
