### ISSUE TITLE
[Source Request] MangaWindow.club

### ISSUE THREAD

**Issue by shashank-p** [inorichi/tachiyomi-extensions#2941] opened 2020-04-30 06:55 UTC
### Source Website
https://mangawindow.club/

### Other Details
I found another mirror site for mangawindow it is different from which is present in mangatensei extension old one is with .net domain

**Comment by SnakeDoc83** [comment] 2020-04-30 07:07
Duplicate of #2871

**Closed** 2020-04-30 11:07 UTC
Labels: Source Request
