### ISSUE TITLE
Filter Mangadex manga in library by group

### ISSUE THREAD

**Issue by bberry1675** [inorichi/tachiyomi-extensions#606] opened 2018-11-07 19:47 UTC
On Mangadex there can be multiple uploads of the same chapter with the same language according to which group uploads a scan. Would it be possible to filter all the chapter in the library by the group so that users don't have to skip over the chapters that they have already read?

**Comment by CarlosEsco** [comment] 2018-11-07 20:08
I don't have the exact ticket number but this a duplicate of one in main repository. It requires a main app change and currently not something being looked at but I know it's been requested a few times

**Closed** 2018-11-07 20:08 UTC
