### ISSUE TITLE
[Bug] <Mangasee (EN)>: <JSON document was not fully consumed>

### ISSUE THREAD

**Issue by Isifferiffa** [inorichi/tachiyomi-extensions#3967] opened 2020-08-01 20:02 UTC
# Device information
- Tachiyomi version: stable 0.10.0
- Android version: 10

### Source information
- Name: mangasee (EN)
- Extension version: 1.2.11

## Steps to reproduce
1. Open mangasee
2. Chapter 350.5 and 99.5 won't download

### Expected behavior
They should have downloaded 

### Actual behavior
They didn't 

### Other details
![Screenshot_20200801-175751_Tachiyomi](https://user-images.githubusercontent.com/69090162/89109570-db8a9580-d431-11ea-93f2-a395e39e4fa8.jpg)

**Comment by E3FxGaming** [comment] 2020-08-06 06:06
@Isifferiffa Could you tell us of which manga Chapter 350.5 and 99.5 won't download? Mangasee has a lot of manga, and I can't reproduce the problem with chapter numbers alone.

**Comment by SnakeDoc83** [comment] 2020-08-07 05:26
Closed by https://github.com/inorichi/tachiyomi-extensions/pull/4027

This probably needs to be applied to MangaLife as well.

**Closed by SnakeDoc83** 2020-08-07 05:26 UTC
Labels: bug
