### ISSUE TITLE
[Bug] <Kiryuu>: <unable to get manga chapter and manga information>

### ISSUE THREAD

**Issue by nizarschecter** [inorichi/tachiyomi-extensions#4496] opened 2020-10-02 12:00 UTC
## Device information
- Tachiyomi version: 0.8.5
- Android version: 4.4.2

## Source information
- Name: Kiryuu
- Extension version: 1.2.2

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by scb261** [comment] 2020-10-02 12:02
Duplicate of #4428

**Closed** 2020-10-02 12:06 UTC
Labels: bug

**Comment by nizarschecter** [comment] 2020-10-02 12:41
> Duplicate of #4428

still unable to

**Comment by arkon** [comment] 2020-10-02 12:44
Do not open duplicate issues.
