### ISSUE TITLE
Webcomics reading limited to first 20 chapters

### ISSUE THREAD

**Issue by haivp3010** [inorichi/tachiyomi-extensions#591] opened 2018-10-28 19:51 UTC
Webcomic extensions can only view first 20 chapters. This is due to the website itself limiting viewers, requiring to install the mobile app. I will look into this to see whether there is a workaround.

Tachiyomi version: 0.8.0
Webcomics extension version: 1.2.1

**Comment by einstein95** [comment] 2018-10-28 19:56
Duplicate of #590

**Closed** 2018-10-28 22:37 UTC
