### ISSUE TITLE
[Source Request] <Gmanga>

### ISSUE THREAD

**Issue by handhsjsj** [inorichi/tachiyomi-extensions#4788] opened 2020-11-04 15:21 UTC
- Name: Gmanga
- Link: https://gmanga.me/
- Language(s): Arabic

**Comment by scb261** [comment] 2020-11-04 15:21
Duplicate of #117

**Closed** 2020-11-04 15:23 UTC
Labels: Source Request

**Comment by handhsjsj** [comment] 2020-11-04 15:25
> Duplicate of #117

Because the other one got closed

**Comment by arkon** [comment] 2020-11-04 16:02
No it didn't...
