### ISSUE TITLE
[Source Request] MangaBlkom Arabic

### ISSUE THREAD

**Issue by ethi** [inorichi/tachiyomi-extensions#1833] opened 2019-11-27 21:39 UTC
### Source Website
Website can be found at <https://manga.blkom.com/>.

**Comment by SnakeDoc83** [comment] 2019-11-27 22:07
Don't spam.

Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/1832

**Closed** 2019-11-27 22:20 UTC
Labels: Source Request
