### ISSUE TITLE
[Source Request] <Tappytoon>

### ISSUE THREAD

**Issue by seaharbour** [inorichi/tachiyomi-extensions#4764] opened 2020-11-02 02:17 UTC
## Tappytoon
- Name: Tappytoon
- Link: https://www.tappytoon.com
- Language(s): English, French, Dutch

**Comment by CrepeTF** [comment] 2020-11-02 06:15
Duplicate of [#1342](https://github.com/inorichi/tachiyomi-extensions/issues/1342)

**Comment by seaharbour** [comment] 2020-11-02 10:25
What do I do with the icons?

**Closed** 2020-11-02 13:00 UTC
Labels: Source Request

**Comment by Soitora** [comment] 2020-11-02 13:36
> What do I do with the icons?

They're for the source request, not for you.

**Comment by Osama-Ezz** [comment] 2020-12-17 19:47
> Duplicate of [#1342](https://github.com/inorichi/tachiyomi-extensions/issues/1342)

If you want me to remove it i will do it.
