### ISSUE TITLE
[Source Request] Rocaca

### ISSUE THREAD

**Issue by saturnedlexx** [inorichi/tachiyomi-extensions#3362] opened 2020-05-31 13:07 UTC
### Source Website
- Name: Rocaca
- Link: Rocaca.com
- Language(s): English

**Comment by SnakeDoc83** [comment] 2020-05-31 20:49
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/587

**Closed by SnakeDoc83** 2020-05-31 20:49 UTC
Labels: Source Request
