### ISSUE TITLE
[Bug] Kissmanga : java.lang.Exception: Challenge not found

### ISSUE THREAD

**Issue by QuietusWolfe** [inorichi/tachiyomi-extensions#2038] opened 2020-01-10 18:52 UTC
* Tachiyomi extension version: 1.2.9
* Tachiyomi version: 0.8.4
* Android version: Fire OS 5.3.6.4 (626533320)

## Steps to reproduce
Try to open any chapter of any manga
OR
Try to open the sources catalog 

### Expected behavior
Chapter/list should open as normal

### Actual behavior
Chapter attempts to load and then shows the "challenge not found" error

In app browers can open the site and chapters as normal, and doesn't ask for a challenge/

**Comment by xzns** [comment] 2020-01-13 19:55
Same issue.
Tachiyomi 0.8.4
Extension 1.2.9
Android 5.1.1

**Comment by Oopstheresaknifeinmydick** [comment] 2020-01-15 07:15
I am having the same issue, only extra info I can provide is that when I open webview sometimes kissmanga opens without CSS and when I press a chapter I either get an ad or a bunch of Cloudflare loading screens where the pages are, then after the loading is done placeholder images appear.

**Comment by arkon** [comment] 2020-01-16 03:25
Duplicate of #2076

**Closed by arkon** 2020-01-16 03:25 UTC
Labels: bug
