### ISSUE TITLE
[Source Request] Kill Six Billion Demons.

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi-extensions#3428] opened 2020-06-07 03:41 UTC
### Source Website
- Name: Kill Six Billion Demons.
- Link: https://killsixbilliondemons.com/
- Language(s): English.

### Other Details
Super cool webcomic which would be great to read from a more comfortable mobile interface like Tachiyomi's. Please consider it, thanks.

**Comment by SnakeDoc83** [comment] 2020-06-07 03:57
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/1588

**Closed by SnakeDoc83** 2020-06-07 03:57 UTC
Labels: Source Request
