### ISSUE TITLE
[Bug] Wakamics: chapters not updating or loading

### ISSUE THREAD

**Issue by minnoao** [inorichi/tachiyomi-extensions#4740] opened 2020-10-29 01:19 UTC
## Device information
- Tachiyomi version: 0.10.5
- Android version: 8.0

## Source information
- Name: Wakamics
- Extension version: Madara 1.2.149

## Steps to reproduce
1. Browse latest in Wakamics source
2. Click on any update

### Expected behavior
Manga should be updated and chapters would load. 
![Screenshot_20201028-210917_Tachiyomi](https://user-images.githubusercontent.com/73622594/97513569-01590500-1963-11eb-80e6-24507b7d70e8.jpg)
![Screenshot_20201028-210908_Tachiyomi](https://user-images.githubusercontent.com/73622594/97513581-0a49d680-1963-11eb-9ca5-1c6072d551bf.jpg)

### Actual behavior
Chapters aren't updated for favourited manga (and can't be read). Other manga will say no chapters have been found.

**Comment by scb261** [comment] 2020-10-29 06:34
Duplicate of #4518

**Closed** 2020-10-29 12:22 UTC
Labels: bug
