### ISSUE TITLE
[Source Request] <Komikmama>

### ISSUE THREAD

**Issue by willyreza** [inorichi/tachiyomi-extensions#4007] opened 2020-08-04 11:56 UTC
### Source Website
- Name: Komikmama
- Link: http://komikmama.net
- Language(s): Indonesian

### Other Details

😊😊😊

**Comment by AbdullahM0hamed** [comment] 2020-10-03 19:37
Duplicate of #3287

**Closed** 2020-10-03 19:48 UTC
Labels: Source Request
