### ISSUE TITLE
[Mangadex] 403 on browse and anything else

### ISSUE THREAD

**Issue by feelerman** [inorichi/tachiyomi-extensions#1027] opened 2019-04-14 16:02 UTC
cannot use webview to solve captcha because no source can be accessed even when looking at "latest"

tachiyomi 0.84 mangadex 1.2.54 android 8.1.0
latest dev version of tachiyomi also does not work.

**Comment by joseph619** [comment] 2019-04-14 17:04
Duplicate of #871

**Closed** 2019-04-14 17:06 UTC
