### ISSUE TITLE
[Bug] OnManga : wont load the manga

### ISSUE THREAD

**Issue by Slowxzy** [inorichi/tachiyomi-extensions#3235] opened 2020-05-19 07:03 UTC
Device information
- Tachiyomi version: stable 0.9.2
- Android version: android 10

 Source information
- Name: madara (OnManga)
- Extension version: 1.2.94

 Steps to reproduce
1. Open OnMnaga
2. Choose a manga
3. Try to read it 

 Expected behavior
 It will load the images so that you can read it

 Actual behavior
 It showed me the retry button 

 Other details
 When I tried to read the manga from the webview it was perfectly normal

**Comment by SnakeDoc83** [comment] 2020-05-19 08:14
Do you have an example title + chapter number you can provide? They're loading for me.

**Comment by Slowxzy** [comment] 2020-05-21 01:59
Currently it says that there isn't any address associated with the hostname

**Comment by Slowxzy** [comment] 2020-05-21 02:03
It currently says that there isnt any address associated with the hostname

**Comment by SnakeDoc83** [comment] 2020-05-21 02:58
Explain in greater detail or post a screenshot.

**Comment by Slowxzy** [comment] 2020-05-21 21:19
How do I post a screenshot?

**Comment by Slowxzy** [comment] 2020-05-21 21:24
![Screenshot_20200521-045636_Tachiyomi](https://user-images.githubusercontent.com/60755830/82607940-73623c80-9bc2-11ea-96b8-cf947319d6e6.jpg)
 
![Screenshot_20200522-001838_Tachiyomi](https://user-images.githubusercontent.com/60755830/82607962-807f2b80-9bc2-11ea-908f-1677e1e042e7.jpg)

![Screenshot_20200522-001901_Tachiyomi](https://user-images.githubusercontent.com/60755830/82607975-870da300-9bc2-11ea-8b8d-97c3df2cfe2e.jpg)

The first screenshot was taken before the update

**Comment by SnakeDoc83** [comment] 2020-05-23 02:18
I can't reproduce. Do the images show in webview?

**Comment by SnakeDoc83** [comment] 2020-06-14 03:55
Closing, nowhere to go with this.

**Closed by SnakeDoc83** 2020-06-14 03:55 UTC
Labels: bug
