### ISSUE TITLE
[Source Request] GoComics

### ISSUE THREAD

**Issue by littlebabyboo** [inorichi/tachiyomi-extensions#3111] opened 2020-05-11 05:59 UTC
- Name: GoComics
- Link: gocomics.com
- Language(s): English

**Comment by arkon** [comment] 2020-05-11 11:48
Duplicate of #1343

**Closed** 2020-05-11 11:48 UTC
Labels: Source Request

**Comment by littlebabyboo** [comment] 2020-05-15 10:55
can you tell me which extension gocomics is? @arkon

**Comment by muekoeff** [comment] 2020-05-20 15:00
@littlebabyboo There's no extension yet. But somebody has already requested one before you.
