### ISSUE TITLE
Support submanga

### ISSUE THREAD

**Issue by vilaroo** [inorichi/tachiyomi-extensions#409] opened 2018-07-23 11:45 UTC
Or any extension in Spanish please!

**Comment by arkon** [comment] 2018-08-09 23:51
https://submanga.online/

**Comment by vilaroo** [comment] 2018-08-10 11:53
Yeah! Add it to tachiyomi!

**Comment by CarlosEsco** [comment] 2018-08-10 20:07
Dupe of #133

**Closed** 2018-08-10 20:07 UTC
