### ISSUE TITLE
[English] readcomics.website

### ISSUE THREAD

**Issue by somevik** [inorichi/tachiyomi-extensions#98] opened 2017-08-25 09:16 UTC
(CATALOGUE) SOURCE REQUESTS:
  One source per issue, create more issues if you have more websites
  Check for duplicates, use search (in issues, not the global one)
  Put the name of the site as Title, replace this text with clickable link to the site
BUGS:
  Provide tachiyomi version as well as version of source the report is about

**Comment by somevik** [comment] 2017-08-25 09:29
http://readcomics.website

**Comment by j2ghz** [comment] 2017-08-26 12:58
Duplicate of #77

**Closed** 2018-03-17 20:54 UTC
Labels: Source Request
