### ISSUE TITLE
[Source Request] mangacanblog

### ISSUE THREAD

**Issue by nizarschecter** [inorichi/tachiyomi-extensions#3372] opened 2020-06-01 22:34 UTC
### Source Website
- Name: mangacanblog
- Link: https://mangacanblog.com
- Language(s): bahasa indonesia

### Other Details

**Comment by SnakeDoc83** [comment] 2020-06-01 22:46
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/465

**Closed by SnakeDoc83** 2020-06-01 22:46 UTC
Labels: Source Request
