### ISSUE TITLE
Can't load some mangas from Kuaikanmanhua. "out must not be null"

### ISSUE THREAD

**Issue by Lovestar98** [inorichi/tachiyomi-extensions#1729] opened 2019-11-01 09:31 UTC
This keeps happening for some of the mangas from this source. There is no problem reading it on the browser though. 

Kuaikanmanhua (快看漫画)
Version: 1.2.1 
Language: 中文 (Chinese)
Tachiyomi app version 0.8.4

![Screenshot_2019-11-01-17-16-53-12](https://user-images.githubusercontent.com/55808462/68015267-bc0ce380-fccc-11e9-960d-03ff310bf73e.png)
![Screenshot_2019-11-01-17-16-49-07](https://user-images.githubusercontent.com/55808462/68015271-bdd6a700-fccc-11e9-9f33-efa7f73b3972.png)

**Comment by happywillow0** [comment] 2019-11-01 16:56
I have a fix in the works but I'm trying to iron out a small bug because some of the chapters are out of order and I'm having a little trouble figuring out why.

**Comment by SnakeDoc83** [comment] 2019-11-01 17:16
Looks like this is caused by chapters which have javscript links.  They're paid chapters; so although this can and should be fixed, those chapters won't be readable.

**Closed** 2019-11-01 21:10 UTC
Labels: bug
